// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.6
// source: cloud/cloudbuild/v1/data.proto

package cloudbuilddata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Possible status of a build or build step.
type BuildEventData_Status int32

const (
	// Status of the build is unknown.
	BuildEventData_STATUS_UNKNOWN BuildEventData_Status = 0
	// Build or step is queued; work has not yet begun.
	BuildEventData_QUEUED BuildEventData_Status = 1
	// Build or step is being executed.
	BuildEventData_WORKING BuildEventData_Status = 2
	// Build or step finished successfully.
	BuildEventData_SUCCESS BuildEventData_Status = 3
	// Build or step failed to complete successfully.
	BuildEventData_FAILURE BuildEventData_Status = 4
	// Build or step failed due to an internal cause.
	BuildEventData_INTERNAL_ERROR BuildEventData_Status = 5
	// Build or step took longer than was allowed.
	BuildEventData_TIMEOUT BuildEventData_Status = 6
	// Build or step was canceled by a user.
	BuildEventData_CANCELLED BuildEventData_Status = 7
	// Build was enqueued for longer than the value of `queue_ttl`.
	BuildEventData_EXPIRED BuildEventData_Status = 9
)

// Enum value maps for BuildEventData_Status.
var (
	BuildEventData_Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "QUEUED",
		2: "WORKING",
		3: "SUCCESS",
		4: "FAILURE",
		5: "INTERNAL_ERROR",
		6: "TIMEOUT",
		7: "CANCELLED",
		9: "EXPIRED",
	}
	BuildEventData_Status_value = map[string]int32{
		"STATUS_UNKNOWN": 0,
		"QUEUED":         1,
		"WORKING":        2,
		"SUCCESS":        3,
		"FAILURE":        4,
		"INTERNAL_ERROR": 5,
		"TIMEOUT":        6,
		"CANCELLED":      7,
		"EXPIRED":        9,
	}
)

func (x BuildEventData_Status) Enum() *BuildEventData_Status {
	p := new(BuildEventData_Status)
	*p = x
	return p
}

func (x BuildEventData_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildEventData_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_cloudbuild_v1_data_proto_enumTypes[0].Descriptor()
}

func (BuildEventData_Status) Type() protoreflect.EnumType {
	return &file_cloud_cloudbuild_v1_data_proto_enumTypes[0]
}

func (x BuildEventData_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildEventData_Status.Descriptor instead.
func (BuildEventData_Status) EnumDescriptor() ([]byte, []int) {
	return file_cloud_cloudbuild_v1_data_proto_rawDescGZIP(), []int{0, 0}
}

// Specifies the hash algorithm, if any.
type Hash_HashType int32

const (
	// No hash requested.
	Hash_NONE Hash_HashType = 0
	// Use a sha256 hash.
	Hash_SHA256 Hash_HashType = 1
	// Use a md5 hash.
	Hash_MD5 Hash_HashType = 2
)

// Enum value maps for Hash_HashType.
var (
	Hash_HashType_name = map[int32]string{
		0: "NONE",
		1: "SHA256",
		2: "MD5",
	}
	Hash_HashType_value = map[string]int32{
		"NONE":   0,
		"SHA256": 1,
		"MD5":    2,
	}
)

func (x Hash_HashType) Enum() *Hash_HashType {
	p := new(Hash_HashType)
	*p = x
	return p
}

func (x Hash_HashType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Hash_HashType) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_cloudbuild_v1_data_proto_enumTypes[1].Descriptor()
}

func (Hash_HashType) Type() protoreflect.EnumType {
	return &file_cloud_cloudbuild_v1_data_proto_enumTypes[1]
}

func (x Hash_HashType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Hash_HashType.Descriptor instead.
func (Hash_HashType) EnumDescriptor() ([]byte, []int) {
	return file_cloud_cloudbuild_v1_data_proto_rawDescGZIP(), []int{12, 0}
}

// Specifies the manner in which the build should be verified, if at all.
type BuildOptions_VerifyOption int32

const (
	// Not a verifiable build. (default)
	BuildOptions_NOT_VERIFIED BuildOptions_VerifyOption = 0
	// Verified build.
	BuildOptions_VERIFIED BuildOptions_VerifyOption = 1
)

// Enum value maps for BuildOptions_VerifyOption.
var (
	BuildOptions_VerifyOption_name = map[int32]string{
		0: "NOT_VERIFIED",
		1: "VERIFIED",
	}
	BuildOptions_VerifyOption_value = map[string]int32{
		"NOT_VERIFIED": 0,
		"VERIFIED":     1,
	}
)

func (x BuildOptions_VerifyOption) Enum() *BuildOptions_VerifyOption {
	p := new(BuildOptions_VerifyOption)
	*p = x
	return p
}

func (x BuildOptions_VerifyOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildOptions_VerifyOption) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_cloudbuild_v1_data_proto_enumTypes[2].Descriptor()
}

func (BuildOptions_VerifyOption) Type() protoreflect.EnumType {
	return &file_cloud_cloudbuild_v1_data_proto_enumTypes[2]
}

func (x BuildOptions_VerifyOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildOptions_VerifyOption.Descriptor instead.
func (BuildOptions_VerifyOption) EnumDescriptor() ([]byte, []int) {
	return file_cloud_cloudbuild_v1_data_proto_rawDescGZIP(), []int{14, 0}
}

// Supported VM sizes.
type BuildOptions_MachineType int32

const (
	// Standard machine type.
	BuildOptions_UNSPECIFIED BuildOptions_MachineType = 0
	// Highcpu machine with 8 CPUs.
	BuildOptions_N1_HIGHCPU_8 BuildOptions_MachineType = 1
	// Highcpu machine with 32 CPUs.
	BuildOptions_N1_HIGHCPU_32 BuildOptions_MachineType = 2
)

// Enum value maps for BuildOptions_MachineType.
var (
	BuildOptions_MachineType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "N1_HIGHCPU_8",
		2: "N1_HIGHCPU_32",
	}
	BuildOptions_MachineType_value = map[string]int32{
		"UNSPECIFIED":   0,
		"N1_HIGHCPU_8":  1,
		"N1_HIGHCPU_32": 2,
	}
)

func (x BuildOptions_MachineType) Enum() *BuildOptions_MachineType {
	p := new(BuildOptions_MachineType)
	*p = x
	return p
}

func (x BuildOptions_MachineType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildOptions_MachineType) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_cloudbuild_v1_data_proto_enumTypes[3].Descriptor()
}

func (BuildOptions_MachineType) Type() protoreflect.EnumType {
	return &file_cloud_cloudbuild_v1_data_proto_enumTypes[3]
}

func (x BuildOptions_MachineType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildOptions_MachineType.Descriptor instead.
func (BuildOptions_MachineType) EnumDescriptor() ([]byte, []int) {
	return file_cloud_cloudbuild_v1_data_proto_rawDescGZIP(), []int{14, 1}
}

// Specifies the behavior when there is an error in the substitution checks.
type BuildOptions_SubstitutionOption int32

const (
	// Fails the build if error in substitutions checks, like missing
	// a substitution in the template or in the map.
	BuildOptions_MUST_MATCH BuildOptions_SubstitutionOption = 0
	// Do not fail the build if error in substitutions checks.
	BuildOptions_ALLOW_LOOSE BuildOptions_SubstitutionOption = 1
)

// Enum value maps for BuildOptions_SubstitutionOption.
var (
	BuildOptions_SubstitutionOption_name = map[int32]string{
		0: "MUST_MATCH",
		1: "ALLOW_LOOSE",
	}
	BuildOptions_SubstitutionOption_value = map[string]int32{
		"MUST_MATCH":  0,
		"ALLOW_LOOSE": 1,
	}
)

func (x BuildOptions_SubstitutionOption) Enum() *BuildOptions_SubstitutionOption {
	p := new(BuildOptions_SubstitutionOption)
	*p = x
	return p
}

func (x BuildOptions_SubstitutionOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildOptions_SubstitutionOption) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_cloudbuild_v1_data_proto_enumTypes[4].Descriptor()
}

func (BuildOptions_SubstitutionOption) Type() protoreflect.EnumType {
	return &file_cloud_cloudbuild_v1_data_proto_enumTypes[4]
}

func (x BuildOptions_SubstitutionOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildOptions_SubstitutionOption.Descriptor instead.
func (BuildOptions_SubstitutionOption) EnumDescriptor() ([]byte, []int) {
	return file_cloud_cloudbuild_v1_data_proto_rawDescGZIP(), []int{14, 2}
}

// Specifies the behavior when writing build logs to Google Cloud Storage.
type BuildOptions_LogStreamingOption int32

const (
	// Service may automatically determine build log streaming behavior.
	BuildOptions_STREAM_DEFAULT BuildOptions_LogStreamingOption = 0
	// Build logs should be streamed to Google Cloud Storage.
	BuildOptions_STREAM_ON BuildOptions_LogStreamingOption = 1
	// Build logs should not be streamed to Google Cloud Storage; they will be
	// written when the build is completed.
	BuildOptions_STREAM_OFF BuildOptions_LogStreamingOption = 2
)

// Enum value maps for BuildOptions_LogStreamingOption.
var (
	BuildOptions_LogStreamingOption_name = map[int32]string{
		0: "STREAM_DEFAULT",
		1: "STREAM_ON",
		2: "STREAM_OFF",
	}
	BuildOptions_LogStreamingOption_value = map[string]int32{
		"STREAM_DEFAULT": 0,
		"STREAM_ON":      1,
		"STREAM_OFF":     2,
	}
)

func (x BuildOptions_LogStreamingOption) Enum() *BuildOptions_LogStreamingOption {
	p := new(BuildOptions_LogStreamingOption)
	*p = x
	return p
}

func (x BuildOptions_LogStreamingOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildOptions_LogStreamingOption) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_cloudbuild_v1_data_proto_enumTypes[5].Descriptor()
}

func (BuildOptions_LogStreamingOption) Type() protoreflect.EnumType {
	return &file_cloud_cloudbuild_v1_data_proto_enumTypes[5]
}

func (x BuildOptions_LogStreamingOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildOptions_LogStreamingOption.Descriptor instead.
func (BuildOptions_LogStreamingOption) EnumDescriptor() ([]byte, []int) {
	return file_cloud_cloudbuild_v1_data_proto_rawDescGZIP(), []int{14, 3}
}

// Specifies the logging mode.
type BuildOptions_LoggingMode int32

const (
	// The service determines the logging mode. The default is `LEGACY`. Do not
	// rely on the default logging behavior as it may change in the future.
	BuildOptions_LOGGING_UNSPECIFIED BuildOptions_LoggingMode = 0
	// Stackdriver logging and Cloud Storage logging are enabled.
	BuildOptions_LEGACY BuildOptions_LoggingMode = 1
	// Only Cloud Storage logging is enabled.
	BuildOptions_GCS_ONLY BuildOptions_LoggingMode = 2
)

// Enum value maps for BuildOptions_LoggingMode.
var (
	BuildOptions_LoggingMode_name = map[int32]string{
		0: "LOGGING_UNSPECIFIED",
		1: "LEGACY",
		2: "GCS_ONLY",
	}
	BuildOptions_LoggingMode_value = map[string]int32{
		"LOGGING_UNSPECIFIED": 0,
		"LEGACY":              1,
		"GCS_ONLY":            2,
	}
)

func (x BuildOptions_LoggingMode) Enum() *BuildOptions_LoggingMode {
	p := new(BuildOptions_LoggingMode)
	*p = x
	return p
}

func (x BuildOptions_LoggingMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildOptions_LoggingMode) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_cloudbuild_v1_data_proto_enumTypes[6].Descriptor()
}

func (BuildOptions_LoggingMode) Type() protoreflect.EnumType {
	return &file_cloud_cloudbuild_v1_data_proto_enumTypes[6]
}

func (x BuildOptions_LoggingMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildOptions_LoggingMode.Descriptor instead.
func (BuildOptions_LoggingMode) EnumDescriptor() ([]byte, []int) {
	return file_cloud_cloudbuild_v1_data_proto_rawDescGZIP(), []int{14, 4}
}

// Build event data for Google Cloud Platform API operations.
type BuildEventData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the build.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// ID of the project.
	ProjectId string `protobuf:"bytes,16,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Status of the build.
	Status BuildEventData_Status `protobuf:"varint,2,opt,name=status,proto3,enum=google.events.cloud.cloudbuild.v1.BuildEventData_Status" json:"status,omitempty"`
	// Customer-readable message about the current status.
	StatusDetail string `protobuf:"bytes,24,opt,name=status_detail,json=statusDetail,proto3" json:"status_detail,omitempty"`
	// The location of the source files to build.
	Source *Source `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// The operations to be performed on the workspace.
	Steps []*BuildStep `protobuf:"bytes,11,rep,name=steps,proto3" json:"steps,omitempty"`
	// Results of the build.
	Results *Results `protobuf:"bytes,10,opt,name=results,proto3" json:"results,omitempty"`
	// Time at which the request to create the build was received.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Time at which execution of the build was started.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Time at which execution of the build was finished.
	//
	// The difference between finish_time and start_time is the duration of the
	// build's execution.
	FinishTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=finish_time,json=finishTime,proto3" json:"finish_time,omitempty"`
	// Amount of time that this build should be allowed to run, to second
	// granularity. If this amount of time elapses, work on the build will cease
	// and the build status will be `TIMEOUT`.
	Timeout *durationpb.Duration `protobuf:"bytes,12,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// A list of images to be pushed upon the successful completion of all build
	// steps.
	//
	// The images are pushed using the builder service account's credentials.
	//
	// The digests of the pushed images will be stored in the `Build` resource's
	// results field.
	//
	// If any of the images fail to be pushed, the build status is marked
	// `FAILURE`.
	Images []string `protobuf:"bytes,13,rep,name=images,proto3" json:"images,omitempty"`
	// TTL in queue for this build. If provided and the build is enqueued longer
	// than this value, the build will expire and the build status will be
	// `EXPIRED`.
	//
	// The TTL starts ticking from create_time.
	QueueTtl *durationpb.Duration `protobuf:"bytes,40,opt,name=queue_ttl,json=queueTtl,proto3" json:"queue_ttl,omitempty"`
	// Artifacts produced by the build that should be uploaded upon
	// successful completion of all build steps.
	Artifacts *Artifacts `protobuf:"bytes,37,opt,name=artifacts,proto3" json:"artifacts,omitempty"`
	// Google Cloud Storage bucket where logs should be written (see
	// [Bucket Name
	// Requirements](https://cloud.google.com/storage/docs/bucket-naming#requirements)).
	// Logs file names will be of the format `${logs_bucket}/log-${build_id}.txt`.
	LogsBucket string `protobuf:"bytes,19,opt,name=logs_bucket,json=logsBucket,proto3" json:"logs_bucket,omitempty"`
	// A permanent fixed identifier for source.
	SourceProvenance *SourceProvenance `protobuf:"bytes,21,opt,name=source_provenance,json=sourceProvenance,proto3" json:"source_provenance,omitempty"`
	// The ID of the `BuildTrigger` that triggered this build, if it
	// was triggered automatically.
	BuildTriggerId string `protobuf:"bytes,22,opt,name=build_trigger_id,json=buildTriggerId,proto3" json:"build_trigger_id,omitempty"`
	// Special options for this build.
	Options *BuildOptions `protobuf:"bytes,23,opt,name=options,proto3" json:"options,omitempty"`
	// URL to logs for this build in Google Cloud Console.
	LogUrl string `protobuf:"bytes,25,opt,name=log_url,json=logUrl,proto3" json:"log_url,omitempty"`
	// Substitutions data for `Build` resource.
	Substitutions map[string]string `protobuf:"bytes,29,rep,name=substitutions,proto3" json:"substitutions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Tags for annotation of a `Build`. These are not docker tags.
	Tags []string `protobuf:"bytes,31,rep,name=tags,proto3" json:"tags,omitempty"`
	// Secrets to decrypt using Cloud Key Management Service.
	Secrets []*Secret `protobuf:"bytes,32,rep,name=secrets,proto3" json:"secrets,omitempty"`
	// Stores timing information for phases of the build. Valid keys
	// are:
	//
	// * BUILD: time to execute all build steps
	// * PUSH: time to push all specified images.
	// * FETCHSOURCE: time to fetch source.
	//
	// If the build does not specify source or images,
	// these keys will not be included.
	Timing        map[string]*TimeSpan `protobuf:"bytes,33,rep,name=timing,proto3" json:"timing,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildEventData) Reset() {
	*x = BuildEventData{}
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildEventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildEventData) ProtoMessage() {}

func (x *BuildEventData) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildEventData.ProtoReflect.Descriptor instead.
func (*BuildEventData) Descriptor() ([]byte, []int) {
	return file_cloud_cloudbuild_v1_data_proto_rawDescGZIP(), []int{0}
}

func (x *BuildEventData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BuildEventData) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *BuildEventData) GetStatus() BuildEventData_Status {
	if x != nil {
		return x.Status
	}
	return BuildEventData_STATUS_UNKNOWN
}

func (x *BuildEventData) GetStatusDetail() string {
	if x != nil {
		return x.StatusDetail
	}
	return ""
}

func (x *BuildEventData) GetSource() *Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *BuildEventData) GetSteps() []*BuildStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *BuildEventData) GetResults() *Results {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *BuildEventData) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *BuildEventData) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *BuildEventData) GetFinishTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishTime
	}
	return nil
}

func (x *BuildEventData) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *BuildEventData) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *BuildEventData) GetQueueTtl() *durationpb.Duration {
	if x != nil {
		return x.QueueTtl
	}
	return nil
}

func (x *BuildEventData) GetArtifacts() *Artifacts {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *BuildEventData) GetLogsBucket() string {
	if x != nil {
		return x.LogsBucket
	}
	return ""
}

func (x *BuildEventData) GetSourceProvenance() *SourceProvenance {
	if x != nil {
		return x.SourceProvenance
	}
	return nil
}

func (x *BuildEventData) GetBuildTriggerId() string {
	if x != nil {
		return x.BuildTriggerId
	}
	return ""
}

func (x *BuildEventData) GetOptions() *BuildOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *BuildEventData) GetLogUrl() string {
	if x != nil {
		return x.LogUrl
	}
	return ""
}

func (x *BuildEventData) GetSubstitutions() map[string]string {
	if x != nil {
		return x.Substitutions
	}
	return nil
}

func (x *BuildEventData) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *BuildEventData) GetSecrets() []*Secret {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *BuildEventData) GetTiming() map[string]*TimeSpan {
	if x != nil {
		return x.Timing
	}
	return nil
}

type Source struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Location of source.
	//
	// Types that are valid to be assigned to Source:
	//
	//	*Source_StorageSource
	//	*Source_RepoSource
	Source        isSource_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_cloud_cloudbuild_v1_data_proto_rawDescGZIP(), []int{1}
}

func (x *Source) GetSource() isSource_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Source) GetStorageSource() *StorageSource {
	if x != nil {
		if x, ok := x.Source.(*Source_StorageSource); ok {
			return x.StorageSource
		}
	}
	return nil
}

func (x *Source) GetRepoSource() *RepoSource {
	if x != nil {
		if x, ok := x.Source.(*Source_RepoSource); ok {
			return x.RepoSource
		}
	}
	return nil
}

type isSource_Source interface {
	isSource_Source()
}

type Source_StorageSource struct {
	// If provided, get the source from this location in Google Cloud Storage.
	StorageSource *StorageSource `protobuf:"bytes,2,opt,name=storage_source,json=storageSource,proto3,oneof"`
}

type Source_RepoSource struct {
	// If provided, get the source from this location in a Cloud Source
	// Repository.
	RepoSource *RepoSource `protobuf:"bytes,3,opt,name=repo_source,json=repoSource,proto3,oneof"`
}

func (*Source_StorageSource) isSource_Source() {}

func (*Source_RepoSource) isSource_Source() {}

// Location of the source in an archive file in Google Cloud Storage.
type StorageSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Google Cloud Storage bucket containing the source (see
	// [Bucket Name
	// Requirements](https://cloud.google.com/storage/docs/bucket-naming#requirements)).
	Bucket string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	// Google Cloud Storage object containing the source.
	Object string `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	// Google Cloud Storage generation for the object. If the generation is
	// omitted, the latest generation will be used.
	Generation    int64 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageSource) Reset() {
	*x = StorageSource{}
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageSource) ProtoMessage() {}

func (x *StorageSource) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageSource.ProtoReflect.Descriptor instead.
func (*StorageSource) Descriptor() ([]byte, []int) {
	return file_cloud_cloudbuild_v1_data_proto_rawDescGZIP(), []int{2}
}

func (x *StorageSource) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *StorageSource) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *StorageSource) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

// Location of the source in a Google Cloud Source Repository.
type RepoSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the project that owns the Cloud Source Repository.
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Name of the Cloud Source Repository.
	RepoName string `protobuf:"bytes,2,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	// A revision within the Cloud Source Repository must be specified in
	// one of these ways.
	//
	// Types that are valid to be assigned to Revision:
	//
	//	*RepoSource_BranchName
	//	*RepoSource_TagName
	//	*RepoSource_CommitSha
	Revision isRepoSource_Revision `protobuf_oneof:"revision"`
	// Directory, relative to the source root, in which to run the build.
	//
	// This must be a relative path. If a step's `dir` is specified and is an
	// absolute path, this value is ignored for that step's execution.
	Dir string `protobuf:"bytes,7,opt,name=dir,proto3" json:"dir,omitempty"`
	// Only trigger a build if the revision regex does NOT match the revision
	// regex.
	InvertRegex bool `protobuf:"varint,8,opt,name=invert_regex,json=invertRegex,proto3" json:"invert_regex,omitempty"`
	// Substitutions to use in a triggered build.
	// Should only be used with RunBuildTrigger
	Substitutions map[string]string `protobuf:"bytes,9,rep,name=substitutions,proto3" json:"substitutions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoSource) Reset() {
	*x = RepoSource{}
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoSource) ProtoMessage() {}

func (x *RepoSource) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoSource.ProtoReflect.Descriptor instead.
func (*RepoSource) Descriptor() ([]byte, []int) {
	return file_cloud_cloudbuild_v1_data_proto_rawDescGZIP(), []int{3}
}

func (x *RepoSource) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *RepoSource) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

func (x *RepoSource) GetRevision() isRepoSource_Revision {
	if x != nil {
		return x.Revision
	}
	return nil
}

func (x *RepoSource) GetBranchName() string {
	if x != nil {
		if x, ok := x.Revision.(*RepoSource_BranchName); ok {
			return x.BranchName
		}
	}
	return ""
}

func (x *RepoSource) GetTagName() string {
	if x != nil {
		if x, ok := x.Revision.(*RepoSource_TagName); ok {
			return x.TagName
		}
	}
	return ""
}

func (x *RepoSource) GetCommitSha() string {
	if x != nil {
		if x, ok := x.Revision.(*RepoSource_CommitSha); ok {
			return x.CommitSha
		}
	}
	return ""
}

func (x *RepoSource) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *RepoSource) GetInvertRegex() bool {
	if x != nil {
		return x.InvertRegex
	}
	return false
}

func (x *RepoSource) GetSubstitutions() map[string]string {
	if x != nil {
		return x.Substitutions
	}
	return nil
}

type isRepoSource_Revision interface {
	isRepoSource_Revision()
}

type RepoSource_BranchName struct {
	// Regex matching branches to build.
	//
	// The syntax of the regular expressions accepted is the syntax accepted by
	// RE2 and described at https://github.com/google/re2/wiki/Syntax
	BranchName string `protobuf:"bytes,3,opt,name=branch_name,json=branchName,proto3,oneof"`
}

type RepoSource_TagName struct {
	// Regex matching tags to build.
	//
	// The syntax of the regular expressions accepted is the syntax accepted by
	// RE2 and described at https://github.com/google/re2/wiki/Syntax
	TagName string `protobuf:"bytes,4,opt,name=tag_name,json=tagName,proto3,oneof"`
}

type RepoSource_CommitSha struct {
	// Explicit commit SHA to build.
	CommitSha string `protobuf:"bytes,5,opt,name=commit_sha,json=commitSha,proto3,oneof"`
}

func (*RepoSource_BranchName) isRepoSource_Revision() {}

func (*RepoSource_TagName) isRepoSource_Revision() {}

func (*RepoSource_CommitSha) isRepoSource_Revision() {}

// A step in the build pipeline.
type BuildStep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the container image that will run this particular
	// build step.
	//
	// If the image is available in the host's Docker daemon's cache, it
	// will be run directly. If not, the host will attempt to pull the image
	// first, using the builder service account's credentials if necessary.
	//
	// The Docker daemon's cache will already have the latest versions of all of
	// the officially supported build steps
	// ([https://github.com/GoogleCloudPlatform/cloud-builders](https://github.com/GoogleCloudPlatform/cloud-builders)).
	// The Docker daemon will also have cached many of the layers for some popular
	// images, like "ubuntu", "debian", but they will be refreshed at the time you
	// attempt to use them.
	//
	// If you built an image in a previous build step, it will be stored in the
	// host's Docker daemon's cache and is available to use as the name for a
	// later build step.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A list of environment variable definitions to be used when running a step.
	//
	// The elements are of the form "KEY=VALUE" for the environment variable "KEY"
	// being given the value "VALUE".
	Env []string `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty"`
	// A list of arguments that will be presented to the step when it is started.
	//
	// If the image used to run the step's container has an entrypoint, the `args`
	// are used as arguments to that entrypoint. If the image does not define
	// an entrypoint, the first element in args is used as the entrypoint,
	// and the remainder will be used as arguments.
	Args []string `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	// Working directory to use when running this step's container.
	//
	// If this value is a relative path, it is relative to the build's working
	// directory. If this value is absolute, it may be outside the build's working
	// directory, in which case the contents of the path may not be persisted
	// across build step executions, unless a `volume` for that path is specified.
	//
	// If the build specifies a `RepoSource` with `dir` and a step with a `dir`,
	// which specifies an absolute path, the `RepoSource` `dir` is ignored for
	// the step's execution.
	Dir string `protobuf:"bytes,4,opt,name=dir,proto3" json:"dir,omitempty"`
	// Unique identifier for this build step, used in `wait_for` to
	// reference this build step as a dependency.
	Id string `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	// The ID(s) of the step(s) that this build step depends on.
	// This build step will not start until all the build steps in `wait_for`
	// have completed successfully. If `wait_for` is empty, this build step will
	// start when all previous build steps in the `Build.Steps` list have
	// completed successfully.
	WaitFor []string `protobuf:"bytes,6,rep,name=wait_for,json=waitFor,proto3" json:"wait_for,omitempty"`
	// Entrypoint to be used instead of the build step image's default entrypoint.
	// If unset, the image's default entrypoint is used.
	Entrypoint string `protobuf:"bytes,7,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	// A list of environment variables which are encrypted using a Cloud Key
	// Management Service crypto key. These values must be specified in the
	// build's `Secret`.
	SecretEnv []string `protobuf:"bytes,8,rep,name=secret_env,json=secretEnv,proto3" json:"secret_env,omitempty"`
	// List of volumes to mount into the build step.
	//
	// Each volume is created as an empty volume prior to execution of the
	// build step. Upon completion of the build, volumes and their contents are
	// discarded.
	//
	// Using a named volume in only one step is not valid as it is indicative
	// of a build request with an incorrect configuration.
	Volumes []*Volume `protobuf:"bytes,9,rep,name=volumes,proto3" json:"volumes,omitempty"`
	// Stores timing information for executing this build step.
	Timing *TimeSpan `protobuf:"bytes,10,opt,name=timing,proto3" json:"timing,omitempty"`
	// Stores timing information for pulling this build step's
	// builder image only.
	PullTiming *TimeSpan `protobuf:"bytes,13,opt,name=pull_timing,json=pullTiming,proto3" json:"pull_timing,omitempty"`
	// Time limit for executing this build step. If not defined, the step has no
	// time limit and will be allowed to continue to run until either it completes
	// or the build itself times out.
	Timeout *durationpb.Duration `protobuf:"bytes,11,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Status of the build step. At this time, build step status is
	// only updated on build completion; step status is not updated in real-time
	// as the build progresses.
	Status        BuildEventData_Status `protobuf:"varint,12,opt,name=status,proto3,enum=google.events.cloud.cloudbuild.v1.BuildEventData_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildStep) Reset() {
	*x = BuildStep{}
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildStep) ProtoMessage() {}

func (x *BuildStep) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildStep.ProtoReflect.Descriptor instead.
func (*BuildStep) Descriptor() ([]byte, []int) {
	return file_cloud_cloudbuild_v1_data_proto_rawDescGZIP(), []int{4}
}

func (x *BuildStep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BuildStep) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *BuildStep) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *BuildStep) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *BuildStep) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BuildStep) GetWaitFor() []string {
	if x != nil {
		return x.WaitFor
	}
	return nil
}

func (x *BuildStep) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

func (x *BuildStep) GetSecretEnv() []string {
	if x != nil {
		return x.SecretEnv
	}
	return nil
}

func (x *BuildStep) GetVolumes() []*Volume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *BuildStep) GetTiming() *TimeSpan {
	if x != nil {
		return x.Timing
	}
	return nil
}

func (x *BuildStep) GetPullTiming() *TimeSpan {
	if x != nil {
		return x.PullTiming
	}
	return nil
}

func (x *BuildStep) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *BuildStep) GetStatus() BuildEventData_Status {
	if x != nil {
		return x.Status
	}
	return BuildEventData_STATUS_UNKNOWN
}

// Volume describes a Docker container volume which is mounted into build steps
// in order to persist files across build step execution.
type Volume struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the volume to mount.
	//
	// Volume names must be unique per build step and must be valid names for
	// Docker volumes. Each named volume must be used by at least two build steps.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Path at which to mount the volume.
	//
	// Paths must be absolute and cannot conflict with other volume paths on the
	// same build step or with certain reserved volume paths.
	Path          string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Volume) Reset() {
	*x = Volume{}
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_cloud_cloudbuild_v1_data_proto_rawDescGZIP(), []int{5}
}

func (x *Volume) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Volume) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Artifacts created by the build pipeline.
type Results struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container images that were built as a part of the build.
	Images []*BuiltImage `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"`
	// List of build step digests, in the order corresponding to build step
	// indices.
	BuildStepImages []string `protobuf:"bytes,3,rep,name=build_step_images,json=buildStepImages,proto3" json:"build_step_images,omitempty"`
	// Path to the artifact manifest. Only populated when artifacts are uploaded.
	ArtifactManifest string `protobuf:"bytes,4,opt,name=artifact_manifest,json=artifactManifest,proto3" json:"artifact_manifest,omitempty"`
	// Number of artifacts uploaded. Only populated when artifacts are uploaded.
	NumArtifacts int64 `protobuf:"varint,5,opt,name=num_artifacts,json=numArtifacts,proto3" json:"num_artifacts,omitempty"`
	// List of build step outputs, produced by builder images, in the order
	// corresponding to build step indices.
	//
	// [Cloud Builders](https://cloud.google.com/cloud-build/docs/cloud-builders)
	// can produce this output by writing to `$BUILDER_OUTPUT/output`.
	// Only the first 4KB of data is stored.
	BuildStepOutputs [][]byte `protobuf:"bytes,6,rep,name=build_step_outputs,json=buildStepOutputs,proto3" json:"build_step_outputs,omitempty"`
	// Time to push all non-container artifacts.
	ArtifactTiming *TimeSpan `protobuf:"bytes,7,opt,name=artifact_timing,json=artifactTiming,proto3" json:"artifact_timing,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Results) Reset() {
	*x = Results{}
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Results) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Results) ProtoMessage() {}

func (x *Results) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Results.ProtoReflect.Descriptor instead.
func (*Results) Descriptor() ([]byte, []int) {
	return file_cloud_cloudbuild_v1_data_proto_rawDescGZIP(), []int{6}
}

func (x *Results) GetImages() []*BuiltImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Results) GetBuildStepImages() []string {
	if x != nil {
		return x.BuildStepImages
	}
	return nil
}

func (x *Results) GetArtifactManifest() string {
	if x != nil {
		return x.ArtifactManifest
	}
	return ""
}

func (x *Results) GetNumArtifacts() int64 {
	if x != nil {
		return x.NumArtifacts
	}
	return 0
}

func (x *Results) GetBuildStepOutputs() [][]byte {
	if x != nil {
		return x.BuildStepOutputs
	}
	return nil
}

func (x *Results) GetArtifactTiming() *TimeSpan {
	if x != nil {
		return x.ArtifactTiming
	}
	return nil
}

// An image built by the pipeline.
type BuiltImage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name used to push the container image to Google Container Registry, as
	// presented to `docker push`.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Docker Registry 2.0 digest.
	Digest string `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	// Stores timing information for pushing the specified image.
	PushTiming    *TimeSpan `protobuf:"bytes,4,opt,name=push_timing,json=pushTiming,proto3" json:"push_timing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuiltImage) Reset() {
	*x = BuiltImage{}
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuiltImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuiltImage) ProtoMessage() {}

func (x *BuiltImage) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuiltImage.ProtoReflect.Descriptor instead.
func (*BuiltImage) Descriptor() ([]byte, []int) {
	return file_cloud_cloudbuild_v1_data_proto_rawDescGZIP(), []int{7}
}

func (x *BuiltImage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BuiltImage) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *BuiltImage) GetPushTiming() *TimeSpan {
	if x != nil {
		return x.PushTiming
	}
	return nil
}

// Artifacts produced by a build that should be uploaded upon
// successful completion of all build steps.
type Artifacts struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of images to be pushed upon the successful completion of all build
	// steps.
	//
	// The images will be pushed using the builder service account's credentials.
	//
	// The digests of the pushed images will be stored in the Build resource's
	// results field.
	//
	// If any of the images fail to be pushed, the build is marked FAILURE.
	Images []string `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	// A list of objects to be uploaded to Cloud Storage upon successful
	// completion of all build steps.
	//
	// Files in the workspace matching specified paths globs will be uploaded to
	// the specified Cloud Storage location using the builder service account's
	// credentials.
	//
	// The location and generation of the uploaded objects will be stored in the
	// Build resource's results field.
	//
	// If any objects fail to be pushed, the build is marked FAILURE.
	Objects       *Artifacts_ArtifactObjects `protobuf:"bytes,2,opt,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifacts) Reset() {
	*x = Artifacts{}
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifacts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifacts) ProtoMessage() {}

func (x *Artifacts) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifacts.ProtoReflect.Descriptor instead.
func (*Artifacts) Descriptor() ([]byte, []int) {
	return file_cloud_cloudbuild_v1_data_proto_rawDescGZIP(), []int{8}
}

func (x *Artifacts) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Artifacts) GetObjects() *Artifacts_ArtifactObjects {
	if x != nil {
		return x.Objects
	}
	return nil
}

// Start and end times for a build execution phase.
type TimeSpan struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start of time span.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// End of time span.
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSpan) Reset() {
	*x = TimeSpan{}
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSpan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSpan) ProtoMessage() {}

func (x *TimeSpan) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSpan.ProtoReflect.Descriptor instead.
func (*TimeSpan) Descriptor() ([]byte, []int) {
	return file_cloud_cloudbuild_v1_data_proto_rawDescGZIP(), []int{9}
}

func (x *TimeSpan) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *TimeSpan) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// Provenance of the source. Ways to find the original source, or verify that
// some source was used for this build.
type SourceProvenance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A copy of the build's `source.storage_source`, if exists, with any
	// generations resolved.
	ResolvedStorageSource *StorageSource `protobuf:"bytes,3,opt,name=resolved_storage_source,json=resolvedStorageSource,proto3" json:"resolved_storage_source,omitempty"`
	// A copy of the build's `source.repo_source`, if exists, with any
	// revisions resolved.
	ResolvedRepoSource *RepoSource `protobuf:"bytes,6,opt,name=resolved_repo_source,json=resolvedRepoSource,proto3" json:"resolved_repo_source,omitempty"`
	// Hash(es) of the build source, which can be used to verify that
	// the original source integrity was maintained in the build. Note that
	// `FileHashes` will only be populated if `BuildOptions` has requested a
	// `SourceProvenanceHash`.
	//
	// The keys to this map are file paths used as build source and the values
	// contain the hash values for those files.
	//
	// If the build source came in a single package such as a gzipped tarfile
	// (`.tar.gz`), the `FileHash` will be for the single path to that file.
	FileHashes    map[string]*FileHashes `protobuf:"bytes,4,rep,name=file_hashes,json=fileHashes,proto3" json:"file_hashes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceProvenance) Reset() {
	*x = SourceProvenance{}
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceProvenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceProvenance) ProtoMessage() {}

func (x *SourceProvenance) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceProvenance.ProtoReflect.Descriptor instead.
func (*SourceProvenance) Descriptor() ([]byte, []int) {
	return file_cloud_cloudbuild_v1_data_proto_rawDescGZIP(), []int{10}
}

func (x *SourceProvenance) GetResolvedStorageSource() *StorageSource {
	if x != nil {
		return x.ResolvedStorageSource
	}
	return nil
}

func (x *SourceProvenance) GetResolvedRepoSource() *RepoSource {
	if x != nil {
		return x.ResolvedRepoSource
	}
	return nil
}

func (x *SourceProvenance) GetFileHashes() map[string]*FileHashes {
	if x != nil {
		return x.FileHashes
	}
	return nil
}

// Container message for hashes of byte content of files, used in
// SourceProvenance messages to verify integrity of source input to the build.
type FileHashes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Collection of file hashes.
	FileHash      []*Hash `protobuf:"bytes,1,rep,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileHashes) Reset() {
	*x = FileHashes{}
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileHashes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileHashes) ProtoMessage() {}

func (x *FileHashes) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileHashes.ProtoReflect.Descriptor instead.
func (*FileHashes) Descriptor() ([]byte, []int) {
	return file_cloud_cloudbuild_v1_data_proto_rawDescGZIP(), []int{11}
}

func (x *FileHashes) GetFileHash() []*Hash {
	if x != nil {
		return x.FileHash
	}
	return nil
}

// Container message for hash values.
type Hash struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of hash that was performed.
	Type Hash_HashType `protobuf:"varint,1,opt,name=type,proto3,enum=google.events.cloud.cloudbuild.v1.Hash_HashType" json:"type,omitempty"`
	// The hash value.
	Value         []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hash) Reset() {
	*x = Hash{}
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hash) ProtoMessage() {}

func (x *Hash) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hash.ProtoReflect.Descriptor instead.
func (*Hash) Descriptor() ([]byte, []int) {
	return file_cloud_cloudbuild_v1_data_proto_rawDescGZIP(), []int{12}
}

func (x *Hash) GetType() Hash_HashType {
	if x != nil {
		return x.Type
	}
	return Hash_NONE
}

func (x *Hash) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// Pairs a set of secret environment variables containing encrypted
// values with the Cloud KMS key to use to decrypt the value.
type Secret struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cloud KMS key name to use to decrypt these envs.
	KmsKeyName string `protobuf:"bytes,1,opt,name=kms_key_name,json=kmsKeyName,proto3" json:"kms_key_name,omitempty"`
	// Map of environment variable name to its encrypted value.
	//
	// Secret environment variables must be unique across all of a build's
	// secrets, and must be used by at least one build step. Values can be at most
	// 64 KB in size. There can be at most 100 secret values across all of a
	// build's secrets.
	SecretEnv     map[string][]byte `protobuf:"bytes,3,rep,name=secret_env,json=secretEnv,proto3" json:"secret_env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_cloud_cloudbuild_v1_data_proto_rawDescGZIP(), []int{13}
}

func (x *Secret) GetKmsKeyName() string {
	if x != nil {
		return x.KmsKeyName
	}
	return ""
}

func (x *Secret) GetSecretEnv() map[string][]byte {
	if x != nil {
		return x.SecretEnv
	}
	return nil
}

// Optional arguments to enable specific features of builds.
type BuildOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Requested hash for SourceProvenance.
	SourceProvenanceHash []Hash_HashType `protobuf:"varint,1,rep,packed,name=source_provenance_hash,json=sourceProvenanceHash,proto3,enum=google.events.cloud.cloudbuild.v1.Hash_HashType" json:"source_provenance_hash,omitempty"`
	// Requested verifiability options.
	RequestedVerifyOption BuildOptions_VerifyOption `protobuf:"varint,2,opt,name=requested_verify_option,json=requestedVerifyOption,proto3,enum=google.events.cloud.cloudbuild.v1.BuildOptions_VerifyOption" json:"requested_verify_option,omitempty"`
	// Compute Engine machine type on which to run the build.
	MachineType BuildOptions_MachineType `protobuf:"varint,3,opt,name=machine_type,json=machineType,proto3,enum=google.events.cloud.cloudbuild.v1.BuildOptions_MachineType" json:"machine_type,omitempty"`
	// Requested disk size for the VM that runs the build. Note that this is *NOT*
	// "disk free"; some of the space will be used by the operating system and
	// build utilities. Also note that this is the minimum disk size that will be
	// allocated for the build -- the build may run with a larger disk than
	// requested. At present, the maximum disk size is 1000GB; builds that request
	// more than the maximum are rejected with an error.
	DiskSizeGb int64 `protobuf:"varint,6,opt,name=disk_size_gb,json=diskSizeGb,proto3" json:"disk_size_gb,omitempty"`
	// Option to specify behavior when there is an error in the substitution
	// checks.
	SubstitutionOption BuildOptions_SubstitutionOption `protobuf:"varint,4,opt,name=substitution_option,json=substitutionOption,proto3,enum=google.events.cloud.cloudbuild.v1.BuildOptions_SubstitutionOption" json:"substitution_option,omitempty"`
	// Option to define build log streaming behavior to Google Cloud
	// Storage.
	LogStreamingOption BuildOptions_LogStreamingOption `protobuf:"varint,5,opt,name=log_streaming_option,json=logStreamingOption,proto3,enum=google.events.cloud.cloudbuild.v1.BuildOptions_LogStreamingOption" json:"log_streaming_option,omitempty"`
	// Option to specify a `WorkerPool` for the build.
	// Format: projects/{project}/locations/{location}/workerPools/{workerPool}
	WorkerPool string `protobuf:"bytes,7,opt,name=worker_pool,json=workerPool,proto3" json:"worker_pool,omitempty"`
	// Option to specify the logging mode, which determines where the logs are
	// stored.
	Logging BuildOptions_LoggingMode `protobuf:"varint,11,opt,name=logging,proto3,enum=google.events.cloud.cloudbuild.v1.BuildOptions_LoggingMode" json:"logging,omitempty"`
	// A list of global environment variable definitions that will exist for all
	// build steps in this build. If a variable is defined in both globally and in
	// a build step, the variable will use the build step value.
	//
	// The elements are of the form "KEY=VALUE" for the environment variable "KEY"
	// being given the value "VALUE".
	Env []string `protobuf:"bytes,12,rep,name=env,proto3" json:"env,omitempty"`
	// A list of global environment variables, which are encrypted using a Cloud
	// Key Management Service crypto key. These values must be specified in the
	// build's `Secret`. These variables will be available to all build steps
	// in this build.
	SecretEnv []string `protobuf:"bytes,13,rep,name=secret_env,json=secretEnv,proto3" json:"secret_env,omitempty"`
	// Global list of volumes to mount for ALL build steps
	//
	// Each volume is created as an empty volume prior to starting the build
	// process. Upon completion of the build, volumes and their contents are
	// discarded. Global volume names and paths cannot conflict with the volumes
	// defined a build step.
	//
	// Using a global volume in a build with only one step is not valid as
	// it is indicative of a build request with an incorrect configuration.
	Volumes       []*Volume `protobuf:"bytes,14,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildOptions) Reset() {
	*x = BuildOptions{}
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildOptions) ProtoMessage() {}

func (x *BuildOptions) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildOptions.ProtoReflect.Descriptor instead.
func (*BuildOptions) Descriptor() ([]byte, []int) {
	return file_cloud_cloudbuild_v1_data_proto_rawDescGZIP(), []int{14}
}

func (x *BuildOptions) GetSourceProvenanceHash() []Hash_HashType {
	if x != nil {
		return x.SourceProvenanceHash
	}
	return nil
}

func (x *BuildOptions) GetRequestedVerifyOption() BuildOptions_VerifyOption {
	if x != nil {
		return x.RequestedVerifyOption
	}
	return BuildOptions_NOT_VERIFIED
}

func (x *BuildOptions) GetMachineType() BuildOptions_MachineType {
	if x != nil {
		return x.MachineType
	}
	return BuildOptions_UNSPECIFIED
}

func (x *BuildOptions) GetDiskSizeGb() int64 {
	if x != nil {
		return x.DiskSizeGb
	}
	return 0
}

func (x *BuildOptions) GetSubstitutionOption() BuildOptions_SubstitutionOption {
	if x != nil {
		return x.SubstitutionOption
	}
	return BuildOptions_MUST_MATCH
}

func (x *BuildOptions) GetLogStreamingOption() BuildOptions_LogStreamingOption {
	if x != nil {
		return x.LogStreamingOption
	}
	return BuildOptions_STREAM_DEFAULT
}

func (x *BuildOptions) GetWorkerPool() string {
	if x != nil {
		return x.WorkerPool
	}
	return ""
}

func (x *BuildOptions) GetLogging() BuildOptions_LoggingMode {
	if x != nil {
		return x.Logging
	}
	return BuildOptions_LOGGING_UNSPECIFIED
}

func (x *BuildOptions) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *BuildOptions) GetSecretEnv() []string {
	if x != nil {
		return x.SecretEnv
	}
	return nil
}

func (x *BuildOptions) GetVolumes() []*Volume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

// Files in the workspace to upload to Cloud Storage upon successful
// completion of all build steps.
type Artifacts_ArtifactObjects struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cloud Storage bucket and optional object path, in the form
	// "gs://bucket/path/to/somewhere/". (see [Bucket Name
	// Requirements](https://cloud.google.com/storage/docs/bucket-naming#requirements)).
	//
	// Files in the workspace matching any path pattern will be uploaded to
	// Cloud Storage with this location as a prefix.
	Location string `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	// Path globs used to match files in the build's workspace.
	Paths []string `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
	// Stores timing information for pushing all artifact objects.
	Timing        *TimeSpan `protobuf:"bytes,3,opt,name=timing,proto3" json:"timing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifacts_ArtifactObjects) Reset() {
	*x = Artifacts_ArtifactObjects{}
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifacts_ArtifactObjects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifacts_ArtifactObjects) ProtoMessage() {}

func (x *Artifacts_ArtifactObjects) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_cloudbuild_v1_data_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifacts_ArtifactObjects.ProtoReflect.Descriptor instead.
func (*Artifacts_ArtifactObjects) Descriptor() ([]byte, []int) {
	return file_cloud_cloudbuild_v1_data_proto_rawDescGZIP(), []int{8, 0}
}

func (x *Artifacts_ArtifactObjects) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Artifacts_ArtifactObjects) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *Artifacts_ArtifactObjects) GetTiming() *TimeSpan {
	if x != nil {
		return x.Timing
	}
	return nil
}

var File_cloud_cloudbuild_v1_data_proto protoreflect.FileDescriptor

const file_cloud_cloudbuild_v1_data_proto_rawDesc = "" +
	"\n" +
	"\x1ecloud/cloudbuild/v1/data.proto\x12!google.events.cloud.cloudbuild.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xef\f\n" +
	"\x0eBuildEventData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x10 \x01(\tR\tprojectId\x12P\n" +
	"\x06status\x18\x02 \x01(\x0e28.google.events.cloud.cloudbuild.v1.BuildEventData.StatusR\x06status\x12#\n" +
	"\rstatus_detail\x18\x18 \x01(\tR\fstatusDetail\x12A\n" +
	"\x06source\x18\x03 \x01(\v2).google.events.cloud.cloudbuild.v1.SourceR\x06source\x12B\n" +
	"\x05steps\x18\v \x03(\v2,.google.events.cloud.cloudbuild.v1.BuildStepR\x05steps\x12D\n" +
	"\aresults\x18\n" +
	" \x01(\v2*.google.events.cloud.cloudbuild.v1.ResultsR\aresults\x12;\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x129\n" +
	"\n" +
	"start_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12;\n" +
	"\vfinish_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishTime\x123\n" +
	"\atimeout\x18\f \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x16\n" +
	"\x06images\x18\r \x03(\tR\x06images\x126\n" +
	"\tqueue_ttl\x18( \x01(\v2\x19.google.protobuf.DurationR\bqueueTtl\x12J\n" +
	"\tartifacts\x18% \x01(\v2,.google.events.cloud.cloudbuild.v1.ArtifactsR\tartifacts\x12\x1f\n" +
	"\vlogs_bucket\x18\x13 \x01(\tR\n" +
	"logsBucket\x12`\n" +
	"\x11source_provenance\x18\x15 \x01(\v23.google.events.cloud.cloudbuild.v1.SourceProvenanceR\x10sourceProvenance\x12(\n" +
	"\x10build_trigger_id\x18\x16 \x01(\tR\x0ebuildTriggerId\x12I\n" +
	"\aoptions\x18\x17 \x01(\v2/.google.events.cloud.cloudbuild.v1.BuildOptionsR\aoptions\x12\x17\n" +
	"\alog_url\x18\x19 \x01(\tR\x06logUrl\x12j\n" +
	"\rsubstitutions\x18\x1d \x03(\v2D.google.events.cloud.cloudbuild.v1.BuildEventData.SubstitutionsEntryR\rsubstitutions\x12\x12\n" +
	"\x04tags\x18\x1f \x03(\tR\x04tags\x12C\n" +
	"\asecrets\x18  \x03(\v2).google.events.cloud.cloudbuild.v1.SecretR\asecrets\x12U\n" +
	"\x06timing\x18! \x03(\v2=.google.events.cloud.cloudbuild.v1.BuildEventData.TimingEntryR\x06timing\x1a@\n" +
	"\x12SubstitutionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1af\n" +
	"\vTimingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12A\n" +
	"\x05value\x18\x02 \x01(\v2+.google.events.cloud.cloudbuild.v1.TimeSpanR\x05value:\x028\x01\"\x8c\x01\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x01\x12\v\n" +
	"\aWORKING\x10\x02\x12\v\n" +
	"\aSUCCESS\x10\x03\x12\v\n" +
	"\aFAILURE\x10\x04\x12\x12\n" +
	"\x0eINTERNAL_ERROR\x10\x05\x12\v\n" +
	"\aTIMEOUT\x10\x06\x12\r\n" +
	"\tCANCELLED\x10\a\x12\v\n" +
	"\aEXPIRED\x10\t\"\xbf\x01\n" +
	"\x06Source\x12Y\n" +
	"\x0estorage_source\x18\x02 \x01(\v20.google.events.cloud.cloudbuild.v1.StorageSourceH\x00R\rstorageSource\x12P\n" +
	"\vrepo_source\x18\x03 \x01(\v2-.google.events.cloud.cloudbuild.v1.RepoSourceH\x00R\n" +
	"repoSourceB\b\n" +
	"\x06source\"_\n" +
	"\rStorageSource\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x03R\n" +
	"generation\"\x94\x03\n" +
	"\n" +
	"RepoSource\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1b\n" +
	"\trepo_name\x18\x02 \x01(\tR\brepoName\x12!\n" +
	"\vbranch_name\x18\x03 \x01(\tH\x00R\n" +
	"branchName\x12\x1b\n" +
	"\btag_name\x18\x04 \x01(\tH\x00R\atagName\x12\x1f\n" +
	"\n" +
	"commit_sha\x18\x05 \x01(\tH\x00R\tcommitSha\x12\x10\n" +
	"\x03dir\x18\a \x01(\tR\x03dir\x12!\n" +
	"\finvert_regex\x18\b \x01(\bR\vinvertRegex\x12f\n" +
	"\rsubstitutions\x18\t \x03(\v2@.google.events.cloud.cloudbuild.v1.RepoSource.SubstitutionsEntryR\rsubstitutions\x1a@\n" +
	"\x12SubstitutionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\n" +
	"\n" +
	"\brevision\"\xa0\x04\n" +
	"\tBuildStep\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03env\x18\x02 \x03(\tR\x03env\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12\x10\n" +
	"\x03dir\x18\x04 \x01(\tR\x03dir\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\x12\x19\n" +
	"\bwait_for\x18\x06 \x03(\tR\awaitFor\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\a \x01(\tR\n" +
	"entrypoint\x12\x1d\n" +
	"\n" +
	"secret_env\x18\b \x03(\tR\tsecretEnv\x12C\n" +
	"\avolumes\x18\t \x03(\v2).google.events.cloud.cloudbuild.v1.VolumeR\avolumes\x12C\n" +
	"\x06timing\x18\n" +
	" \x01(\v2+.google.events.cloud.cloudbuild.v1.TimeSpanR\x06timing\x12L\n" +
	"\vpull_timing\x18\r \x01(\v2+.google.events.cloud.cloudbuild.v1.TimeSpanR\n" +
	"pullTiming\x123\n" +
	"\atimeout\x18\v \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12P\n" +
	"\x06status\x18\f \x01(\x0e28.google.events.cloud.cloudbuild.v1.BuildEventData.StatusR\x06status\"0\n" +
	"\x06Volume\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\xd2\x02\n" +
	"\aResults\x12E\n" +
	"\x06images\x18\x02 \x03(\v2-.google.events.cloud.cloudbuild.v1.BuiltImageR\x06images\x12*\n" +
	"\x11build_step_images\x18\x03 \x03(\tR\x0fbuildStepImages\x12+\n" +
	"\x11artifact_manifest\x18\x04 \x01(\tR\x10artifactManifest\x12#\n" +
	"\rnum_artifacts\x18\x05 \x01(\x03R\fnumArtifacts\x12,\n" +
	"\x12build_step_outputs\x18\x06 \x03(\fR\x10buildStepOutputs\x12T\n" +
	"\x0fartifact_timing\x18\a \x01(\v2+.google.events.cloud.cloudbuild.v1.TimeSpanR\x0eartifactTiming\"\x86\x01\n" +
	"\n" +
	"BuiltImage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\x12L\n" +
	"\vpush_timing\x18\x04 \x01(\v2+.google.events.cloud.cloudbuild.v1.TimeSpanR\n" +
	"pushTiming\"\x86\x02\n" +
	"\tArtifacts\x12\x16\n" +
	"\x06images\x18\x01 \x03(\tR\x06images\x12V\n" +
	"\aobjects\x18\x02 \x01(\v2<.google.events.cloud.cloudbuild.v1.Artifacts.ArtifactObjectsR\aobjects\x1a\x88\x01\n" +
	"\x0fArtifactObjects\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12\x14\n" +
	"\x05paths\x18\x02 \x03(\tR\x05paths\x12C\n" +
	"\x06timing\x18\x03 \x01(\v2+.google.events.cloud.cloudbuild.v1.TimeSpanR\x06timing\"|\n" +
	"\bTimeSpan\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\xb1\x03\n" +
	"\x10SourceProvenance\x12h\n" +
	"\x17resolved_storage_source\x18\x03 \x01(\v20.google.events.cloud.cloudbuild.v1.StorageSourceR\x15resolvedStorageSource\x12_\n" +
	"\x14resolved_repo_source\x18\x06 \x01(\v2-.google.events.cloud.cloudbuild.v1.RepoSourceR\x12resolvedRepoSource\x12d\n" +
	"\vfile_hashes\x18\x04 \x03(\v2C.google.events.cloud.cloudbuild.v1.SourceProvenance.FileHashesEntryR\n" +
	"fileHashes\x1al\n" +
	"\x0fFileHashesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12C\n" +
	"\x05value\x18\x02 \x01(\v2-.google.events.cloud.cloudbuild.v1.FileHashesR\x05value:\x028\x01\"R\n" +
	"\n" +
	"FileHashes\x12D\n" +
	"\tfile_hash\x18\x01 \x03(\v2'.google.events.cloud.cloudbuild.v1.HashR\bfileHash\"\x8d\x01\n" +
	"\x04Hash\x12D\n" +
	"\x04type\x18\x01 \x01(\x0e20.google.events.cloud.cloudbuild.v1.Hash.HashTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\")\n" +
	"\bHashType\x12\b\n" +
	"\x04NONE\x10\x00\x12\n" +
	"\n" +
	"\x06SHA256\x10\x01\x12\a\n" +
	"\x03MD5\x10\x02\"\xc1\x01\n" +
	"\x06Secret\x12 \n" +
	"\fkms_key_name\x18\x01 \x01(\tR\n" +
	"kmsKeyName\x12W\n" +
	"\n" +
	"secret_env\x18\x03 \x03(\v28.google.events.cloud.cloudbuild.v1.Secret.SecretEnvEntryR\tsecretEnv\x1a<\n" +
	"\x0eSecretEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xfe\b\n" +
	"\fBuildOptions\x12f\n" +
	"\x16source_provenance_hash\x18\x01 \x03(\x0e20.google.events.cloud.cloudbuild.v1.Hash.HashTypeR\x14sourceProvenanceHash\x12t\n" +
	"\x17requested_verify_option\x18\x02 \x01(\x0e2<.google.events.cloud.cloudbuild.v1.BuildOptions.VerifyOptionR\x15requestedVerifyOption\x12^\n" +
	"\fmachine_type\x18\x03 \x01(\x0e2;.google.events.cloud.cloudbuild.v1.BuildOptions.MachineTypeR\vmachineType\x12 \n" +
	"\fdisk_size_gb\x18\x06 \x01(\x03R\n" +
	"diskSizeGb\x12s\n" +
	"\x13substitution_option\x18\x04 \x01(\x0e2B.google.events.cloud.cloudbuild.v1.BuildOptions.SubstitutionOptionR\x12substitutionOption\x12t\n" +
	"\x14log_streaming_option\x18\x05 \x01(\x0e2B.google.events.cloud.cloudbuild.v1.BuildOptions.LogStreamingOptionR\x12logStreamingOption\x12\x1f\n" +
	"\vworker_pool\x18\a \x01(\tR\n" +
	"workerPool\x12U\n" +
	"\alogging\x18\v \x01(\x0e2;.google.events.cloud.cloudbuild.v1.BuildOptions.LoggingModeR\alogging\x12\x10\n" +
	"\x03env\x18\f \x03(\tR\x03env\x12\x1d\n" +
	"\n" +
	"secret_env\x18\r \x03(\tR\tsecretEnv\x12C\n" +
	"\avolumes\x18\x0e \x03(\v2).google.events.cloud.cloudbuild.v1.VolumeR\avolumes\".\n" +
	"\fVerifyOption\x12\x10\n" +
	"\fNOT_VERIFIED\x10\x00\x12\f\n" +
	"\bVERIFIED\x10\x01\"C\n" +
	"\vMachineType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x10\n" +
	"\fN1_HIGHCPU_8\x10\x01\x12\x11\n" +
	"\rN1_HIGHCPU_32\x10\x02\"5\n" +
	"\x12SubstitutionOption\x12\x0e\n" +
	"\n" +
	"MUST_MATCH\x10\x00\x12\x0f\n" +
	"\vALLOW_LOOSE\x10\x01\"G\n" +
	"\x12LogStreamingOption\x12\x12\n" +
	"\x0eSTREAM_DEFAULT\x10\x00\x12\r\n" +
	"\tSTREAM_ON\x10\x01\x12\x0e\n" +
	"\n" +
	"STREAM_OFF\x10\x02\"@\n" +
	"\vLoggingMode\x12\x17\n" +
	"\x13LOGGING_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06LEGACY\x10\x01\x12\f\n" +
	"\bGCS_ONLY\x10\x02By\xaa\x02*Google.Events.Protobuf.Cloud.CloudBuild.V1\xca\x02!Google\\Events\\Cloud\\CloudBuild\\V1\xea\x02%Google::Events::Cloud::CloudBuild::V1b\x06proto3"

var (
	file_cloud_cloudbuild_v1_data_proto_rawDescOnce sync.Once
	file_cloud_cloudbuild_v1_data_proto_rawDescData []byte
)

func file_cloud_cloudbuild_v1_data_proto_rawDescGZIP() []byte {
	file_cloud_cloudbuild_v1_data_proto_rawDescOnce.Do(func() {
		file_cloud_cloudbuild_v1_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloud_cloudbuild_v1_data_proto_rawDesc), len(file_cloud_cloudbuild_v1_data_proto_rawDesc)))
	})
	return file_cloud_cloudbuild_v1_data_proto_rawDescData
}

var file_cloud_cloudbuild_v1_data_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_cloud_cloudbuild_v1_data_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_cloud_cloudbuild_v1_data_proto_goTypes = []any{
	(BuildEventData_Status)(0),           // 0: google.events.cloud.cloudbuild.v1.BuildEventData.Status
	(Hash_HashType)(0),                   // 1: google.events.cloud.cloudbuild.v1.Hash.HashType
	(BuildOptions_VerifyOption)(0),       // 2: google.events.cloud.cloudbuild.v1.BuildOptions.VerifyOption
	(BuildOptions_MachineType)(0),        // 3: google.events.cloud.cloudbuild.v1.BuildOptions.MachineType
	(BuildOptions_SubstitutionOption)(0), // 4: google.events.cloud.cloudbuild.v1.BuildOptions.SubstitutionOption
	(BuildOptions_LogStreamingOption)(0), // 5: google.events.cloud.cloudbuild.v1.BuildOptions.LogStreamingOption
	(BuildOptions_LoggingMode)(0),        // 6: google.events.cloud.cloudbuild.v1.BuildOptions.LoggingMode
	(*BuildEventData)(nil),               // 7: google.events.cloud.cloudbuild.v1.BuildEventData
	(*Source)(nil),                       // 8: google.events.cloud.cloudbuild.v1.Source
	(*StorageSource)(nil),                // 9: google.events.cloud.cloudbuild.v1.StorageSource
	(*RepoSource)(nil),                   // 10: google.events.cloud.cloudbuild.v1.RepoSource
	(*BuildStep)(nil),                    // 11: google.events.cloud.cloudbuild.v1.BuildStep
	(*Volume)(nil),                       // 12: google.events.cloud.cloudbuild.v1.Volume
	(*Results)(nil),                      // 13: google.events.cloud.cloudbuild.v1.Results
	(*BuiltImage)(nil),                   // 14: google.events.cloud.cloudbuild.v1.BuiltImage
	(*Artifacts)(nil),                    // 15: google.events.cloud.cloudbuild.v1.Artifacts
	(*TimeSpan)(nil),                     // 16: google.events.cloud.cloudbuild.v1.TimeSpan
	(*SourceProvenance)(nil),             // 17: google.events.cloud.cloudbuild.v1.SourceProvenance
	(*FileHashes)(nil),                   // 18: google.events.cloud.cloudbuild.v1.FileHashes
	(*Hash)(nil),                         // 19: google.events.cloud.cloudbuild.v1.Hash
	(*Secret)(nil),                       // 20: google.events.cloud.cloudbuild.v1.Secret
	(*BuildOptions)(nil),                 // 21: google.events.cloud.cloudbuild.v1.BuildOptions
	nil,                                  // 22: google.events.cloud.cloudbuild.v1.BuildEventData.SubstitutionsEntry
	nil,                                  // 23: google.events.cloud.cloudbuild.v1.BuildEventData.TimingEntry
	nil,                                  // 24: google.events.cloud.cloudbuild.v1.RepoSource.SubstitutionsEntry
	(*Artifacts_ArtifactObjects)(nil),    // 25: google.events.cloud.cloudbuild.v1.Artifacts.ArtifactObjects
	nil,                                  // 26: google.events.cloud.cloudbuild.v1.SourceProvenance.FileHashesEntry
	nil,                                  // 27: google.events.cloud.cloudbuild.v1.Secret.SecretEnvEntry
	(*timestamppb.Timestamp)(nil),        // 28: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),          // 29: google.protobuf.Duration
}
var file_cloud_cloudbuild_v1_data_proto_depIdxs = []int32{
	0,  // 0: google.events.cloud.cloudbuild.v1.BuildEventData.status:type_name -> google.events.cloud.cloudbuild.v1.BuildEventData.Status
	8,  // 1: google.events.cloud.cloudbuild.v1.BuildEventData.source:type_name -> google.events.cloud.cloudbuild.v1.Source
	11, // 2: google.events.cloud.cloudbuild.v1.BuildEventData.steps:type_name -> google.events.cloud.cloudbuild.v1.BuildStep
	13, // 3: google.events.cloud.cloudbuild.v1.BuildEventData.results:type_name -> google.events.cloud.cloudbuild.v1.Results
	28, // 4: google.events.cloud.cloudbuild.v1.BuildEventData.create_time:type_name -> google.protobuf.Timestamp
	28, // 5: google.events.cloud.cloudbuild.v1.BuildEventData.start_time:type_name -> google.protobuf.Timestamp
	28, // 6: google.events.cloud.cloudbuild.v1.BuildEventData.finish_time:type_name -> google.protobuf.Timestamp
	29, // 7: google.events.cloud.cloudbuild.v1.BuildEventData.timeout:type_name -> google.protobuf.Duration
	29, // 8: google.events.cloud.cloudbuild.v1.BuildEventData.queue_ttl:type_name -> google.protobuf.Duration
	15, // 9: google.events.cloud.cloudbuild.v1.BuildEventData.artifacts:type_name -> google.events.cloud.cloudbuild.v1.Artifacts
	17, // 10: google.events.cloud.cloudbuild.v1.BuildEventData.source_provenance:type_name -> google.events.cloud.cloudbuild.v1.SourceProvenance
	21, // 11: google.events.cloud.cloudbuild.v1.BuildEventData.options:type_name -> google.events.cloud.cloudbuild.v1.BuildOptions
	22, // 12: google.events.cloud.cloudbuild.v1.BuildEventData.substitutions:type_name -> google.events.cloud.cloudbuild.v1.BuildEventData.SubstitutionsEntry
	20, // 13: google.events.cloud.cloudbuild.v1.BuildEventData.secrets:type_name -> google.events.cloud.cloudbuild.v1.Secret
	23, // 14: google.events.cloud.cloudbuild.v1.BuildEventData.timing:type_name -> google.events.cloud.cloudbuild.v1.BuildEventData.TimingEntry
	9,  // 15: google.events.cloud.cloudbuild.v1.Source.storage_source:type_name -> google.events.cloud.cloudbuild.v1.StorageSource
	10, // 16: google.events.cloud.cloudbuild.v1.Source.repo_source:type_name -> google.events.cloud.cloudbuild.v1.RepoSource
	24, // 17: google.events.cloud.cloudbuild.v1.RepoSource.substitutions:type_name -> google.events.cloud.cloudbuild.v1.RepoSource.SubstitutionsEntry
	12, // 18: google.events.cloud.cloudbuild.v1.BuildStep.volumes:type_name -> google.events.cloud.cloudbuild.v1.Volume
	16, // 19: google.events.cloud.cloudbuild.v1.BuildStep.timing:type_name -> google.events.cloud.cloudbuild.v1.TimeSpan
	16, // 20: google.events.cloud.cloudbuild.v1.BuildStep.pull_timing:type_name -> google.events.cloud.cloudbuild.v1.TimeSpan
	29, // 21: google.events.cloud.cloudbuild.v1.BuildStep.timeout:type_name -> google.protobuf.Duration
	0,  // 22: google.events.cloud.cloudbuild.v1.BuildStep.status:type_name -> google.events.cloud.cloudbuild.v1.BuildEventData.Status
	14, // 23: google.events.cloud.cloudbuild.v1.Results.images:type_name -> google.events.cloud.cloudbuild.v1.BuiltImage
	16, // 24: google.events.cloud.cloudbuild.v1.Results.artifact_timing:type_name -> google.events.cloud.cloudbuild.v1.TimeSpan
	16, // 25: google.events.cloud.cloudbuild.v1.BuiltImage.push_timing:type_name -> google.events.cloud.cloudbuild.v1.TimeSpan
	25, // 26: google.events.cloud.cloudbuild.v1.Artifacts.objects:type_name -> google.events.cloud.cloudbuild.v1.Artifacts.ArtifactObjects
	28, // 27: google.events.cloud.cloudbuild.v1.TimeSpan.start_time:type_name -> google.protobuf.Timestamp
	28, // 28: google.events.cloud.cloudbuild.v1.TimeSpan.end_time:type_name -> google.protobuf.Timestamp
	9,  // 29: google.events.cloud.cloudbuild.v1.SourceProvenance.resolved_storage_source:type_name -> google.events.cloud.cloudbuild.v1.StorageSource
	10, // 30: google.events.cloud.cloudbuild.v1.SourceProvenance.resolved_repo_source:type_name -> google.events.cloud.cloudbuild.v1.RepoSource
	26, // 31: google.events.cloud.cloudbuild.v1.SourceProvenance.file_hashes:type_name -> google.events.cloud.cloudbuild.v1.SourceProvenance.FileHashesEntry
	19, // 32: google.events.cloud.cloudbuild.v1.FileHashes.file_hash:type_name -> google.events.cloud.cloudbuild.v1.Hash
	1,  // 33: google.events.cloud.cloudbuild.v1.Hash.type:type_name -> google.events.cloud.cloudbuild.v1.Hash.HashType
	27, // 34: google.events.cloud.cloudbuild.v1.Secret.secret_env:type_name -> google.events.cloud.cloudbuild.v1.Secret.SecretEnvEntry
	1,  // 35: google.events.cloud.cloudbuild.v1.BuildOptions.source_provenance_hash:type_name -> google.events.cloud.cloudbuild.v1.Hash.HashType
	2,  // 36: google.events.cloud.cloudbuild.v1.BuildOptions.requested_verify_option:type_name -> google.events.cloud.cloudbuild.v1.BuildOptions.VerifyOption
	3,  // 37: google.events.cloud.cloudbuild.v1.BuildOptions.machine_type:type_name -> google.events.cloud.cloudbuild.v1.BuildOptions.MachineType
	4,  // 38: google.events.cloud.cloudbuild.v1.BuildOptions.substitution_option:type_name -> google.events.cloud.cloudbuild.v1.BuildOptions.SubstitutionOption
	5,  // 39: google.events.cloud.cloudbuild.v1.BuildOptions.log_streaming_option:type_name -> google.events.cloud.cloudbuild.v1.BuildOptions.LogStreamingOption
	6,  // 40: google.events.cloud.cloudbuild.v1.BuildOptions.logging:type_name -> google.events.cloud.cloudbuild.v1.BuildOptions.LoggingMode
	12, // 41: google.events.cloud.cloudbuild.v1.BuildOptions.volumes:type_name -> google.events.cloud.cloudbuild.v1.Volume
	16, // 42: google.events.cloud.cloudbuild.v1.BuildEventData.TimingEntry.value:type_name -> google.events.cloud.cloudbuild.v1.TimeSpan
	16, // 43: google.events.cloud.cloudbuild.v1.Artifacts.ArtifactObjects.timing:type_name -> google.events.cloud.cloudbuild.v1.TimeSpan
	18, // 44: google.events.cloud.cloudbuild.v1.SourceProvenance.FileHashesEntry.value:type_name -> google.events.cloud.cloudbuild.v1.FileHashes
	45, // [45:45] is the sub-list for method output_type
	45, // [45:45] is the sub-list for method input_type
	45, // [45:45] is the sub-list for extension type_name
	45, // [45:45] is the sub-list for extension extendee
	0,  // [0:45] is the sub-list for field type_name
}

func init() { file_cloud_cloudbuild_v1_data_proto_init() }
func file_cloud_cloudbuild_v1_data_proto_init() {
	if File_cloud_cloudbuild_v1_data_proto != nil {
		return
	}
	file_cloud_cloudbuild_v1_data_proto_msgTypes[1].OneofWrappers = []any{
		(*Source_StorageSource)(nil),
		(*Source_RepoSource)(nil),
	}
	file_cloud_cloudbuild_v1_data_proto_msgTypes[3].OneofWrappers = []any{
		(*RepoSource_BranchName)(nil),
		(*RepoSource_TagName)(nil),
		(*RepoSource_CommitSha)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloud_cloudbuild_v1_data_proto_rawDesc), len(file_cloud_cloudbuild_v1_data_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cloud_cloudbuild_v1_data_proto_goTypes,
		DependencyIndexes: file_cloud_cloudbuild_v1_data_proto_depIdxs,
		EnumInfos:         file_cloud_cloudbuild_v1_data_proto_enumTypes,
		MessageInfos:      file_cloud_cloudbuild_v1_data_proto_msgTypes,
	}.Build()
	File_cloud_cloudbuild_v1_data_proto = out.File
	file_cloud_cloudbuild_v1_data_proto_goTypes = nil
	file_cloud_cloudbuild_v1_data_proto_depIdxs = nil
}
