// Copyright 2016 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.6
// source: cloud/audit/v1/data.proto

package auditdata

import (
	api "github.com/googleapis/google-cloudevents-go/third_party/googleapis/google/api"
	attribute_context "google.golang.org/genproto/googleapis/rpc/context/attribute_context"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The severity of the event described in a log entry, expressed as one of the
// standard severity levels listed below.  For your reference, the levels are
// assigned the listed numeric values. The effect of using numeric values other
// than those listed is undefined.
// Copied from
// https://github.com/googleapis/googleapis/blob/master/google/logging/type/log_severity.proto
type LogSeverity int32

const (
	// (0) The log entry has no assigned severity level.
	LogSeverity_DEFAULT LogSeverity = 0
	// (100) Debug or trace information.
	LogSeverity_DEBUG LogSeverity = 100
	// (200) Routine information, such as ongoing status or performance.
	LogSeverity_INFO LogSeverity = 200
	// (300) Normal but significant events, such as start up, shut down, or
	// a configuration change.
	LogSeverity_NOTICE LogSeverity = 300
	// (400) Warning events might cause problems.
	LogSeverity_WARNING LogSeverity = 400
	// (500) Error events are likely to cause problems.
	LogSeverity_ERROR LogSeverity = 500
	// (600) Critical events cause more severe problems or outages.
	LogSeverity_CRITICAL LogSeverity = 600
	// (700) A person must take an action immediately.
	LogSeverity_ALERT LogSeverity = 700
	// (800) One or more systems are unusable.
	LogSeverity_EMERGENCY LogSeverity = 800
)

// Enum value maps for LogSeverity.
var (
	LogSeverity_name = map[int32]string{
		0:   "DEFAULT",
		100: "DEBUG",
		200: "INFO",
		300: "NOTICE",
		400: "WARNING",
		500: "ERROR",
		600: "CRITICAL",
		700: "ALERT",
		800: "EMERGENCY",
	}
	LogSeverity_value = map[string]int32{
		"DEFAULT":   0,
		"DEBUG":     100,
		"INFO":      200,
		"NOTICE":    300,
		"WARNING":   400,
		"ERROR":     500,
		"CRITICAL":  600,
		"ALERT":     700,
		"EMERGENCY": 800,
	}
)

func (x LogSeverity) Enum() *LogSeverity {
	p := new(LogSeverity)
	*p = x
	return p
}

func (x LogSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_audit_v1_data_proto_enumTypes[0].Descriptor()
}

func (LogSeverity) Type() protoreflect.EnumType {
	return &file_cloud_audit_v1_data_proto_enumTypes[0]
}

func (x LogSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogSeverity.Descriptor instead.
func (LogSeverity) EnumDescriptor() ([]byte, []int) {
	return file_cloud_audit_v1_data_proto_rawDescGZIP(), []int{0}
}

// The data within all Cloud Audit Logs log entry events.
type LogEntryData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the log to which this log entry belongs.
	LogName string `protobuf:"bytes,12,opt,name=log_name,json=logName,proto3" json:"log_name,omitempty"`
	// The monitored resource that produced this log entry.
	//
	// Example: a log entry that reports a database error would be associated with
	// the monitored resource designating the particular database that reported
	// the error.
	Resource *api.MonitoredResource `protobuf:"bytes,8,opt,name=resource,proto3" json:"resource,omitempty"`
	// The log entry payload, which is always an AuditLog for Cloud Audit Log
	// events.
	ProtoPayload *AuditLog `protobuf:"bytes,2,opt,name=proto_payload,json=protoPayload,proto3" json:"proto_payload,omitempty"`
	// A unique identifier for the log entry.
	InsertId string `protobuf:"bytes,4,opt,name=insert_id,json=insertId,proto3" json:"insert_id,omitempty"`
	// A set of user-defined (key, value) data that provides additional
	// information about the log entry.
	Labels map[string]string `protobuf:"bytes,11,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Information about an operation associated with the log entry, if
	// applicable.
	Operation *LogEntryOperation `protobuf:"bytes,15,opt,name=operation,proto3" json:"operation,omitempty"`
	// The time the event described by the log entry occurred.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The time the log entry was received by Logging.
	ReceiveTimestamp *timestamppb.Timestamp `protobuf:"bytes,24,opt,name=receive_timestamp,json=receiveTimestamp,proto3" json:"receive_timestamp,omitempty"`
	// The severity of the log entry.
	Severity LogSeverity `protobuf:"varint,10,opt,name=severity,proto3,enum=google.events.cloud.audit.v1.LogSeverity" json:"severity,omitempty"`
	// Resource name of the trace associated with the log entry, if any. If it
	// contains a relative resource name, the name is assumed to be relative to
	// `//tracing.googleapis.com`. Example:
	// `projects/my-projectid/traces/06796866738c859f2f19b7cfb3214824`
	Trace string `protobuf:"bytes,22,opt,name=trace,proto3" json:"trace,omitempty"`
	// The span ID within the trace associated with the log entry, if any.
	//
	// For Trace spans, this is the same format that the Trace API v2 uses: a
	// 16-character hexadecimal encoding of an 8-byte array, such as
	// `000000000000004a`.
	SpanId string `protobuf:"bytes,27,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	// Information indicating this LogEntry is part of a sequence of multiple logs
	// split from a single LogEntry.
	Split         *LogSplit `protobuf:"bytes,35,opt,name=split,proto3" json:"split,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntryData) Reset() {
	*x = LogEntryData{}
	mi := &file_cloud_audit_v1_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntryData) ProtoMessage() {}

func (x *LogEntryData) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_audit_v1_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntryData.ProtoReflect.Descriptor instead.
func (*LogEntryData) Descriptor() ([]byte, []int) {
	return file_cloud_audit_v1_data_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntryData) GetLogName() string {
	if x != nil {
		return x.LogName
	}
	return ""
}

func (x *LogEntryData) GetResource() *api.MonitoredResource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *LogEntryData) GetProtoPayload() *AuditLog {
	if x != nil {
		return x.ProtoPayload
	}
	return nil
}

func (x *LogEntryData) GetInsertId() string {
	if x != nil {
		return x.InsertId
	}
	return ""
}

func (x *LogEntryData) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *LogEntryData) GetOperation() *LogEntryOperation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *LogEntryData) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntryData) GetReceiveTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceiveTimestamp
	}
	return nil
}

func (x *LogEntryData) GetSeverity() LogSeverity {
	if x != nil {
		return x.Severity
	}
	return LogSeverity_DEFAULT
}

func (x *LogEntryData) GetTrace() string {
	if x != nil {
		return x.Trace
	}
	return ""
}

func (x *LogEntryData) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *LogEntryData) GetSplit() *LogSplit {
	if x != nil {
		return x.Split
	}
	return nil
}

// Additional information about a potentially long-running operation with which
// a log entry is associated.
type LogEntryOperation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An arbitrary operation identifier. Log entries with the same
	// identifier are assumed to be part of the same operation.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// An arbitrary producer identifier. The combination of `id` and
	// `producer` must be globally unique. Examples for `producer`:
	// `"MyDivision.MyBigCompany.com"`, `"github.com/MyProject/MyApplication"`.
	Producer string `protobuf:"bytes,2,opt,name=producer,proto3" json:"producer,omitempty"`
	// True if this is the first log entry in the operation.
	First bool `protobuf:"varint,3,opt,name=first,proto3" json:"first,omitempty"`
	// True if this is the last log entry in the operation.
	Last          bool `protobuf:"varint,4,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntryOperation) Reset() {
	*x = LogEntryOperation{}
	mi := &file_cloud_audit_v1_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntryOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntryOperation) ProtoMessage() {}

func (x *LogEntryOperation) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_audit_v1_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntryOperation.ProtoReflect.Descriptor instead.
func (*LogEntryOperation) Descriptor() ([]byte, []int) {
	return file_cloud_audit_v1_data_proto_rawDescGZIP(), []int{1}
}

func (x *LogEntryOperation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LogEntryOperation) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *LogEntryOperation) GetFirst() bool {
	if x != nil {
		return x.First
	}
	return false
}

func (x *LogEntryOperation) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

// Common audit log format for Google Cloud Platform API operations.
// Copied from
// https://github.com/googleapis/googleapis/blob/master/google/cloud/audit/audit_log.proto,
// but changing service_data from Any to Struct.
type AuditLog struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the API service performing the operation. For example,
	// `"datastore.googleapis.com"`.
	ServiceName string `protobuf:"bytes,7,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// The name of the service method or operation.
	// For API calls, this should be the name of the API method.
	// For example,
	//
	//	"google.datastore.v1.Datastore.RunQuery"
	//	"google.logging.v1.LoggingService.DeleteLog"
	MethodName string `protobuf:"bytes,8,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	// The resource or collection that is the target of the operation.
	// The name is a scheme-less URI, not including the API service name.
	// For example:
	//
	//	"shelves/SHELF_ID/books"
	//	"shelves/SHELF_ID/books/BOOK_ID"
	ResourceName string `protobuf:"bytes,11,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	// The resource location information.
	ResourceLocation *ResourceLocation `protobuf:"bytes,20,opt,name=resource_location,json=resourceLocation,proto3" json:"resource_location,omitempty"`
	// The resource's original state before mutation. Present only for
	// operations which have successfully modified the targeted resource(s).
	// In general, this field should contain all changed fields, except those
	// that are already been included in `request`, `response`, `metadata` or
	// `service_data` fields.
	// When the JSON object represented here has a proto equivalent,
	// the proto name will be indicated in the `@type` property.
	ResourceOriginalState *structpb.Struct `protobuf:"bytes,19,opt,name=resource_original_state,json=resourceOriginalState,proto3" json:"resource_original_state,omitempty"`
	// The number of items returned from a List or Query API method,
	// if applicable.
	NumResponseItems int64 `protobuf:"varint,12,opt,name=num_response_items,json=numResponseItems,proto3" json:"num_response_items,omitempty"`
	// The status of the overall operation.
	Status *status.Status `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Authentication information.
	AuthenticationInfo *AuthenticationInfo `protobuf:"bytes,3,opt,name=authentication_info,json=authenticationInfo,proto3" json:"authentication_info,omitempty"`
	// Authorization information. If there are multiple
	// resources or permissions involved, then there is
	// one AuthorizationInfo element for each {resource, permission} tuple.
	AuthorizationInfo []*AuthorizationInfo `protobuf:"bytes,9,rep,name=authorization_info,json=authorizationInfo,proto3" json:"authorization_info,omitempty"`
	// Metadata about the operation.
	RequestMetadata *RequestMetadata `protobuf:"bytes,4,opt,name=request_metadata,json=requestMetadata,proto3" json:"request_metadata,omitempty"`
	// The operation request. This may not include all request parameters,
	// such as those that are too large, privacy-sensitive, or duplicated
	// elsewhere in the log record.
	// It should never include user-generated data, such as file contents.
	// When the JSON object represented here has a proto equivalent, the proto
	// name will be indicated in the `@type` property.
	Request *structpb.Struct `protobuf:"bytes,16,opt,name=request,proto3" json:"request,omitempty"`
	// The operation response. This may not include all response elements,
	// such as those that are too large, privacy-sensitive, or duplicated
	// elsewhere in the log record.
	// It should never include user-generated data, such as file contents.
	// When the JSON object represented here has a proto equivalent, the proto
	// name will be indicated in the `@type` property.
	Response *structpb.Struct `protobuf:"bytes,17,opt,name=response,proto3" json:"response,omitempty"`
	// Other service-specific data about the request, response, and other
	// information associated with the current audited event.
	Metadata *structpb.Struct `protobuf:"bytes,18,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Deprecated: Use `metadata` field instead.
	// Other service-specific data about the request, response, and other
	// activities.
	// When the JSON object represented here has a proto equivalent, the proto
	// name will be indicated in the `@type` property.
	ServiceData   *structpb.Struct `protobuf:"bytes,15,opt,name=service_data,json=serviceData,proto3" json:"service_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLog) Reset() {
	*x = AuditLog{}
	mi := &file_cloud_audit_v1_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLog) ProtoMessage() {}

func (x *AuditLog) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_audit_v1_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLog.ProtoReflect.Descriptor instead.
func (*AuditLog) Descriptor() ([]byte, []int) {
	return file_cloud_audit_v1_data_proto_rawDescGZIP(), []int{2}
}

func (x *AuditLog) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *AuditLog) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *AuditLog) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *AuditLog) GetResourceLocation() *ResourceLocation {
	if x != nil {
		return x.ResourceLocation
	}
	return nil
}

func (x *AuditLog) GetResourceOriginalState() *structpb.Struct {
	if x != nil {
		return x.ResourceOriginalState
	}
	return nil
}

func (x *AuditLog) GetNumResponseItems() int64 {
	if x != nil {
		return x.NumResponseItems
	}
	return 0
}

func (x *AuditLog) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *AuditLog) GetAuthenticationInfo() *AuthenticationInfo {
	if x != nil {
		return x.AuthenticationInfo
	}
	return nil
}

func (x *AuditLog) GetAuthorizationInfo() []*AuthorizationInfo {
	if x != nil {
		return x.AuthorizationInfo
	}
	return nil
}

func (x *AuditLog) GetRequestMetadata() *RequestMetadata {
	if x != nil {
		return x.RequestMetadata
	}
	return nil
}

func (x *AuditLog) GetRequest() *structpb.Struct {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AuditLog) GetResponse() *structpb.Struct {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *AuditLog) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AuditLog) GetServiceData() *structpb.Struct {
	if x != nil {
		return x.ServiceData
	}
	return nil
}

// Authentication information for the operation.
type AuthenticationInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The email address of the authenticated user (or service account on behalf
	// of third party principal) making the request. For third party identity
	// callers, the `principal_subject` field is populated instead of this field.
	// For privacy reasons, the principal email address is sometimes redacted.
	// For more information, see [Caller identities in audit
	// logs](https://cloud.google.com/logging/docs/audit#user-id).
	PrincipalEmail string `protobuf:"bytes,1,opt,name=principal_email,json=principalEmail,proto3" json:"principal_email,omitempty"`
	// The authority selector specified by the requestor, if any.
	// It is not guaranteed that the principal was allowed to use this authority.
	AuthoritySelector string `protobuf:"bytes,2,opt,name=authority_selector,json=authoritySelector,proto3" json:"authority_selector,omitempty"`
	// The third party identification (if any) of the authenticated user making
	// the request.
	// When the JSON object represented here has a proto equivalent, the proto
	// name will be indicated in the `@type` property.
	ThirdPartyPrincipal *structpb.Struct `protobuf:"bytes,4,opt,name=third_party_principal,json=thirdPartyPrincipal,proto3" json:"third_party_principal,omitempty"`
	// The name of the service account key used to create or exchange
	// credentials for authenticating the service account making the request.
	// This is a scheme-less URI full resource name. For example:
	//
	// "//iam.googleapis.com/projects/{PROJECT_ID}/serviceAccounts/{ACCOUNT}/keys/{key}"
	ServiceAccountKeyName string `protobuf:"bytes,5,opt,name=service_account_key_name,json=serviceAccountKeyName,proto3" json:"service_account_key_name,omitempty"`
	// Identity delegation history of an authenticated service account that makes
	// the request. It contains information on the real authorities that try to
	// access GCP resources by delegating on a service account. When multiple
	// authorities present, they are guaranteed to be sorted based on the original
	// ordering of the identity delegation events.
	ServiceAccountDelegationInfo []*ServiceAccountDelegationInfo `protobuf:"bytes,6,rep,name=service_account_delegation_info,json=serviceAccountDelegationInfo,proto3" json:"service_account_delegation_info,omitempty"`
	// String representation of identity of requesting party.
	// Populated for both first and third party identities.
	PrincipalSubject string `protobuf:"bytes,8,opt,name=principal_subject,json=principalSubject,proto3" json:"principal_subject,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthenticationInfo) Reset() {
	*x = AuthenticationInfo{}
	mi := &file_cloud_audit_v1_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationInfo) ProtoMessage() {}

func (x *AuthenticationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_audit_v1_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationInfo.ProtoReflect.Descriptor instead.
func (*AuthenticationInfo) Descriptor() ([]byte, []int) {
	return file_cloud_audit_v1_data_proto_rawDescGZIP(), []int{3}
}

func (x *AuthenticationInfo) GetPrincipalEmail() string {
	if x != nil {
		return x.PrincipalEmail
	}
	return ""
}

func (x *AuthenticationInfo) GetAuthoritySelector() string {
	if x != nil {
		return x.AuthoritySelector
	}
	return ""
}

func (x *AuthenticationInfo) GetThirdPartyPrincipal() *structpb.Struct {
	if x != nil {
		return x.ThirdPartyPrincipal
	}
	return nil
}

func (x *AuthenticationInfo) GetServiceAccountKeyName() string {
	if x != nil {
		return x.ServiceAccountKeyName
	}
	return ""
}

func (x *AuthenticationInfo) GetServiceAccountDelegationInfo() []*ServiceAccountDelegationInfo {
	if x != nil {
		return x.ServiceAccountDelegationInfo
	}
	return nil
}

func (x *AuthenticationInfo) GetPrincipalSubject() string {
	if x != nil {
		return x.PrincipalSubject
	}
	return ""
}

// Authorization information for the operation.
type AuthorizationInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource being accessed, as a REST-style string. For example:
	//
	//	bigquery.googleapis.com/projects/PROJECTID/datasets/DATASETID
	Resource string `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// The required IAM permission.
	Permission string `protobuf:"bytes,2,opt,name=permission,proto3" json:"permission,omitempty"`
	// Whether or not authorization for `resource` and `permission`
	// was granted.
	Granted bool `protobuf:"varint,3,opt,name=granted,proto3" json:"granted,omitempty"`
	// Resource attributes used in IAM condition evaluation. This field contains
	// resource attributes like resource type and resource name.
	//
	// To get the whole view of the attributes used in IAM
	// condition evaluation, the user must also look into
	// `AuditLogData.request_metadata.request_attributes`.
	ResourceAttributes *attribute_context.AttributeContext_Resource `protobuf:"bytes,5,opt,name=resource_attributes,json=resourceAttributes,proto3" json:"resource_attributes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AuthorizationInfo) Reset() {
	*x = AuthorizationInfo{}
	mi := &file_cloud_audit_v1_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationInfo) ProtoMessage() {}

func (x *AuthorizationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_audit_v1_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationInfo.ProtoReflect.Descriptor instead.
func (*AuthorizationInfo) Descriptor() ([]byte, []int) {
	return file_cloud_audit_v1_data_proto_rawDescGZIP(), []int{4}
}

func (x *AuthorizationInfo) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AuthorizationInfo) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *AuthorizationInfo) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

func (x *AuthorizationInfo) GetResourceAttributes() *attribute_context.AttributeContext_Resource {
	if x != nil {
		return x.ResourceAttributes
	}
	return nil
}

// Metadata about the request.
type RequestMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The IP address of the caller.
	// For caller from internet, this will be public IPv4 or IPv6 address.
	// For caller from a Compute Engine VM with external IP address, this
	// will be the VM's external IP address. For caller from a Compute
	// Engine VM without external IP address, if the VM is in the same
	// organization (or project) as the accessed resource, `caller_ip` will
	// be the VM's internal IPv4 address, otherwise the `caller_ip` will be
	// redacted to "gce-internal-ip".
	// See https://cloud.google.com/compute/docs/vpc/ for more information.
	CallerIp string `protobuf:"bytes,1,opt,name=caller_ip,json=callerIp,proto3" json:"caller_ip,omitempty"`
	// The user agent of the caller.
	// This information is not authenticated and should be treated accordingly.
	// For example:
	//
	//   - `google-api-python-client/1.4.0`:
	//     The request was made by the Google API client for Python.
	//   - `Cloud SDK Command Line Tool apitools-client/1.0 gcloud/0.9.62`:
	//     The request was made by the Google Cloud SDK CLI (gcloud).
	//   - `AppEngine-Google; (+http://code.google.com/appengine; appid:
	//
	// s~my-project`:
	//
	//	The request was made from the `my-project` App Engine app.
	CallerSuppliedUserAgent string `protobuf:"bytes,2,opt,name=caller_supplied_user_agent,json=callerSuppliedUserAgent,proto3" json:"caller_supplied_user_agent,omitempty"`
	// The network of the caller.
	// Set only if the network host project is part of the same GCP organization
	// (or project) as the accessed resource.
	// See https://cloud.google.com/compute/docs/vpc/ for more information.
	// This is a scheme-less URI full resource name. For example:
	//
	//	"//compute.googleapis.com/projects/PROJECT_ID/global/networks/NETWORK_ID"
	CallerNetwork string `protobuf:"bytes,3,opt,name=caller_network,json=callerNetwork,proto3" json:"caller_network,omitempty"`
	// Request attributes used in IAM condition evaluation. This field contains
	// request attributes like request time and access levels associated with
	// the request.
	//
	// To get the whole view of the attributes used in IAM
	// condition evaluation, the user must also look into
	// `AuditLog.authentication_info.resource_attributes`.
	RequestAttributes *attribute_context.AttributeContext_Request `protobuf:"bytes,7,opt,name=request_attributes,json=requestAttributes,proto3" json:"request_attributes,omitempty"`
	// The destination of a network activity, such as accepting a TCP connection.
	// In a multi hop network activity, the destination represents the receiver of
	// the last hop. Only two fields are used in this message, Peer.port and
	// Peer.ip. These fields are optionally populated by those services utilizing
	// the IAM condition feature.
	DestinationAttributes *attribute_context.AttributeContext_Peer `protobuf:"bytes,8,opt,name=destination_attributes,json=destinationAttributes,proto3" json:"destination_attributes,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RequestMetadata) Reset() {
	*x = RequestMetadata{}
	mi := &file_cloud_audit_v1_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMetadata) ProtoMessage() {}

func (x *RequestMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_audit_v1_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMetadata.ProtoReflect.Descriptor instead.
func (*RequestMetadata) Descriptor() ([]byte, []int) {
	return file_cloud_audit_v1_data_proto_rawDescGZIP(), []int{5}
}

func (x *RequestMetadata) GetCallerIp() string {
	if x != nil {
		return x.CallerIp
	}
	return ""
}

func (x *RequestMetadata) GetCallerSuppliedUserAgent() string {
	if x != nil {
		return x.CallerSuppliedUserAgent
	}
	return ""
}

func (x *RequestMetadata) GetCallerNetwork() string {
	if x != nil {
		return x.CallerNetwork
	}
	return ""
}

func (x *RequestMetadata) GetRequestAttributes() *attribute_context.AttributeContext_Request {
	if x != nil {
		return x.RequestAttributes
	}
	return nil
}

func (x *RequestMetadata) GetDestinationAttributes() *attribute_context.AttributeContext_Peer {
	if x != nil {
		return x.DestinationAttributes
	}
	return nil
}

// Location information about a resource.
type ResourceLocation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The locations of a resource after the execution of the operation.
	// Requests to create or delete a location based resource must populate
	// the 'current_locations' field and not the 'original_locations' field.
	// For example:
	//
	//	"europe-west1-a"
	//	"us-east1"
	//	"nam3"
	CurrentLocations []string `protobuf:"bytes,1,rep,name=current_locations,json=currentLocations,proto3" json:"current_locations,omitempty"`
	// The locations of a resource prior to the execution of the operation.
	// Requests that mutate the resource's location must populate both the
	// 'original_locations' as well as the 'current_locations' fields.
	// For example:
	//
	//	"europe-west1-a"
	//	"us-east1"
	//	"nam3"
	OriginalLocations []string `protobuf:"bytes,2,rep,name=original_locations,json=originalLocations,proto3" json:"original_locations,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResourceLocation) Reset() {
	*x = ResourceLocation{}
	mi := &file_cloud_audit_v1_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLocation) ProtoMessage() {}

func (x *ResourceLocation) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_audit_v1_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLocation.ProtoReflect.Descriptor instead.
func (*ResourceLocation) Descriptor() ([]byte, []int) {
	return file_cloud_audit_v1_data_proto_rawDescGZIP(), []int{6}
}

func (x *ResourceLocation) GetCurrentLocations() []string {
	if x != nil {
		return x.CurrentLocations
	}
	return nil
}

func (x *ResourceLocation) GetOriginalLocations() []string {
	if x != nil {
		return x.OriginalLocations
	}
	return nil
}

// Identity delegation history of an authenticated service account.
type ServiceAccountDelegationInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Entity that creates credentials for service account and assumes its
	// identity for authentication.
	//
	// Types that are valid to be assigned to Authority:
	//
	//	*ServiceAccountDelegationInfo_FirstPartyPrincipal_
	//	*ServiceAccountDelegationInfo_ThirdPartyPrincipal_
	Authority     isServiceAccountDelegationInfo_Authority `protobuf_oneof:"Authority"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceAccountDelegationInfo) Reset() {
	*x = ServiceAccountDelegationInfo{}
	mi := &file_cloud_audit_v1_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceAccountDelegationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAccountDelegationInfo) ProtoMessage() {}

func (x *ServiceAccountDelegationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_audit_v1_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAccountDelegationInfo.ProtoReflect.Descriptor instead.
func (*ServiceAccountDelegationInfo) Descriptor() ([]byte, []int) {
	return file_cloud_audit_v1_data_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceAccountDelegationInfo) GetAuthority() isServiceAccountDelegationInfo_Authority {
	if x != nil {
		return x.Authority
	}
	return nil
}

func (x *ServiceAccountDelegationInfo) GetFirstPartyPrincipal() *ServiceAccountDelegationInfo_FirstPartyPrincipal {
	if x != nil {
		if x, ok := x.Authority.(*ServiceAccountDelegationInfo_FirstPartyPrincipal_); ok {
			return x.FirstPartyPrincipal
		}
	}
	return nil
}

func (x *ServiceAccountDelegationInfo) GetThirdPartyPrincipal() *ServiceAccountDelegationInfo_ThirdPartyPrincipal {
	if x != nil {
		if x, ok := x.Authority.(*ServiceAccountDelegationInfo_ThirdPartyPrincipal_); ok {
			return x.ThirdPartyPrincipal
		}
	}
	return nil
}

type isServiceAccountDelegationInfo_Authority interface {
	isServiceAccountDelegationInfo_Authority()
}

type ServiceAccountDelegationInfo_FirstPartyPrincipal_ struct {
	// First party (Google) identity as the real authority.
	FirstPartyPrincipal *ServiceAccountDelegationInfo_FirstPartyPrincipal `protobuf:"bytes,1,opt,name=first_party_principal,json=firstPartyPrincipal,proto3,oneof"`
}

type ServiceAccountDelegationInfo_ThirdPartyPrincipal_ struct {
	// Third party identity as the real authority.
	ThirdPartyPrincipal *ServiceAccountDelegationInfo_ThirdPartyPrincipal `protobuf:"bytes,2,opt,name=third_party_principal,json=thirdPartyPrincipal,proto3,oneof"`
}

func (*ServiceAccountDelegationInfo_FirstPartyPrincipal_) isServiceAccountDelegationInfo_Authority() {
}

func (*ServiceAccountDelegationInfo_ThirdPartyPrincipal_) isServiceAccountDelegationInfo_Authority() {
}

// Additional information used to correlate multiple LogEntries. Used when a
// single LogEntry would exceed the Google Cloud Logging size limit and is split
// across multiple entries.
type LogSplit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A globally unique identifier for all LogEntries in a sequence of split
	// logs. All LogEntries with the same |LogSplit.uid| are assumed to be part of
	// the same sequence of split logs.
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// The index of this LogEntry in the sequence of split logs. LogEntries are
	// given |index| values 0, 1, ..., n-1 for a sequence of n entries.
	Index int32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// The total number of logs that the original LogEntry was split into.
	TotalSplits   int32 `protobuf:"varint,3,opt,name=total_splits,json=totalSplits,proto3" json:"total_splits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogSplit) Reset() {
	*x = LogSplit{}
	mi := &file_cloud_audit_v1_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogSplit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSplit) ProtoMessage() {}

func (x *LogSplit) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_audit_v1_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSplit.ProtoReflect.Descriptor instead.
func (*LogSplit) Descriptor() ([]byte, []int) {
	return file_cloud_audit_v1_data_proto_rawDescGZIP(), []int{8}
}

func (x *LogSplit) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *LogSplit) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LogSplit) GetTotalSplits() int32 {
	if x != nil {
		return x.TotalSplits
	}
	return 0
}

// First party identity principal.
type ServiceAccountDelegationInfo_FirstPartyPrincipal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The email address of a Google account.
	PrincipalEmail string `protobuf:"bytes,1,opt,name=principal_email,json=principalEmail,proto3" json:"principal_email,omitempty"`
	// Metadata about the service that uses the service account.
	ServiceMetadata *structpb.Struct `protobuf:"bytes,2,opt,name=service_metadata,json=serviceMetadata,proto3" json:"service_metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServiceAccountDelegationInfo_FirstPartyPrincipal) Reset() {
	*x = ServiceAccountDelegationInfo_FirstPartyPrincipal{}
	mi := &file_cloud_audit_v1_data_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceAccountDelegationInfo_FirstPartyPrincipal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAccountDelegationInfo_FirstPartyPrincipal) ProtoMessage() {}

func (x *ServiceAccountDelegationInfo_FirstPartyPrincipal) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_audit_v1_data_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAccountDelegationInfo_FirstPartyPrincipal.ProtoReflect.Descriptor instead.
func (*ServiceAccountDelegationInfo_FirstPartyPrincipal) Descriptor() ([]byte, []int) {
	return file_cloud_audit_v1_data_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ServiceAccountDelegationInfo_FirstPartyPrincipal) GetPrincipalEmail() string {
	if x != nil {
		return x.PrincipalEmail
	}
	return ""
}

func (x *ServiceAccountDelegationInfo_FirstPartyPrincipal) GetServiceMetadata() *structpb.Struct {
	if x != nil {
		return x.ServiceMetadata
	}
	return nil
}

// Third party identity principal.
type ServiceAccountDelegationInfo_ThirdPartyPrincipal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata about third party identity.
	ThirdPartyClaims *structpb.Struct `protobuf:"bytes,1,opt,name=third_party_claims,json=thirdPartyClaims,proto3" json:"third_party_claims,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServiceAccountDelegationInfo_ThirdPartyPrincipal) Reset() {
	*x = ServiceAccountDelegationInfo_ThirdPartyPrincipal{}
	mi := &file_cloud_audit_v1_data_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceAccountDelegationInfo_ThirdPartyPrincipal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAccountDelegationInfo_ThirdPartyPrincipal) ProtoMessage() {}

func (x *ServiceAccountDelegationInfo_ThirdPartyPrincipal) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_audit_v1_data_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAccountDelegationInfo_ThirdPartyPrincipal.ProtoReflect.Descriptor instead.
func (*ServiceAccountDelegationInfo_ThirdPartyPrincipal) Descriptor() ([]byte, []int) {
	return file_cloud_audit_v1_data_proto_rawDescGZIP(), []int{7, 1}
}

func (x *ServiceAccountDelegationInfo_ThirdPartyPrincipal) GetThirdPartyClaims() *structpb.Struct {
	if x != nil {
		return x.ThirdPartyClaims
	}
	return nil
}

var File_cloud_audit_v1_data_proto protoreflect.FileDescriptor

const file_cloud_audit_v1_data_proto_rawDesc = "" +
	"\n" +
	"\x19cloud/audit/v1/data.proto\x12\x1cgoogle.events.cloud.audit.v1\x1a#google/api/monitored_resource.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a*google/rpc/context/attribute_context.proto\x1a\x17google/rpc/status.proto\"\xdf\x05\n" +
	"\fLogEntryData\x12\x19\n" +
	"\blog_name\x18\f \x01(\tR\alogName\x129\n" +
	"\bresource\x18\b \x01(\v2\x1d.google.api.MonitoredResourceR\bresource\x12K\n" +
	"\rproto_payload\x18\x02 \x01(\v2&.google.events.cloud.audit.v1.AuditLogR\fprotoPayload\x12\x1b\n" +
	"\tinsert_id\x18\x04 \x01(\tR\binsertId\x12N\n" +
	"\x06labels\x18\v \x03(\v26.google.events.cloud.audit.v1.LogEntryData.LabelsEntryR\x06labels\x12M\n" +
	"\toperation\x18\x0f \x01(\v2/.google.events.cloud.audit.v1.LogEntryOperationR\toperation\x128\n" +
	"\ttimestamp\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12G\n" +
	"\x11receive_timestamp\x18\x18 \x01(\v2\x1a.google.protobuf.TimestampR\x10receiveTimestamp\x12E\n" +
	"\bseverity\x18\n" +
	" \x01(\x0e2).google.events.cloud.audit.v1.LogSeverityR\bseverity\x12\x14\n" +
	"\x05trace\x18\x16 \x01(\tR\x05trace\x12\x17\n" +
	"\aspan_id\x18\x1b \x01(\tR\x06spanId\x12<\n" +
	"\x05split\x18# \x01(\v2&.google.events.cloud.audit.v1.LogSplitR\x05split\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"i\n" +
	"\x11LogEntryOperation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bproducer\x18\x02 \x01(\tR\bproducer\x12\x14\n" +
	"\x05first\x18\x03 \x01(\bR\x05first\x12\x12\n" +
	"\x04last\x18\x04 \x01(\bR\x04last\"\xf1\x06\n" +
	"\bAuditLog\x12!\n" +
	"\fservice_name\x18\a \x01(\tR\vserviceName\x12\x1f\n" +
	"\vmethod_name\x18\b \x01(\tR\n" +
	"methodName\x12#\n" +
	"\rresource_name\x18\v \x01(\tR\fresourceName\x12[\n" +
	"\x11resource_location\x18\x14 \x01(\v2..google.events.cloud.audit.v1.ResourceLocationR\x10resourceLocation\x12O\n" +
	"\x17resource_original_state\x18\x13 \x01(\v2\x17.google.protobuf.StructR\x15resourceOriginalState\x12,\n" +
	"\x12num_response_items\x18\f \x01(\x03R\x10numResponseItems\x12*\n" +
	"\x06status\x18\x02 \x01(\v2\x12.google.rpc.StatusR\x06status\x12a\n" +
	"\x13authentication_info\x18\x03 \x01(\v20.google.events.cloud.audit.v1.AuthenticationInfoR\x12authenticationInfo\x12^\n" +
	"\x12authorization_info\x18\t \x03(\v2/.google.events.cloud.audit.v1.AuthorizationInfoR\x11authorizationInfo\x12X\n" +
	"\x10request_metadata\x18\x04 \x01(\v2-.google.events.cloud.audit.v1.RequestMetadataR\x0frequestMetadata\x121\n" +
	"\arequest\x18\x10 \x01(\v2\x17.google.protobuf.StructR\arequest\x123\n" +
	"\bresponse\x18\x11 \x01(\v2\x17.google.protobuf.StructR\bresponse\x123\n" +
	"\bmetadata\x18\x12 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12:\n" +
	"\fservice_data\x18\x0f \x01(\v2\x17.google.protobuf.StructR\vserviceData\"\xa3\x03\n" +
	"\x12AuthenticationInfo\x12'\n" +
	"\x0fprincipal_email\x18\x01 \x01(\tR\x0eprincipalEmail\x12-\n" +
	"\x12authority_selector\x18\x02 \x01(\tR\x11authoritySelector\x12K\n" +
	"\x15third_party_principal\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x13thirdPartyPrincipal\x127\n" +
	"\x18service_account_key_name\x18\x05 \x01(\tR\x15serviceAccountKeyName\x12\x81\x01\n" +
	"\x1fservice_account_delegation_info\x18\x06 \x03(\v2:.google.events.cloud.audit.v1.ServiceAccountDelegationInfoR\x1cserviceAccountDelegationInfo\x12+\n" +
	"\x11principal_subject\x18\b \x01(\tR\x10principalSubject\"\xc9\x01\n" +
	"\x11AuthorizationInfo\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x1e\n" +
	"\n" +
	"permission\x18\x02 \x01(\tR\n" +
	"permission\x12\x18\n" +
	"\agranted\x18\x03 \x01(\bR\agranted\x12^\n" +
	"\x13resource_attributes\x18\x05 \x01(\v2-.google.rpc.context.AttributeContext.ResourceR\x12resourceAttributes\"\xd1\x02\n" +
	"\x0fRequestMetadata\x12\x1b\n" +
	"\tcaller_ip\x18\x01 \x01(\tR\bcallerIp\x12;\n" +
	"\x1acaller_supplied_user_agent\x18\x02 \x01(\tR\x17callerSuppliedUserAgent\x12%\n" +
	"\x0ecaller_network\x18\x03 \x01(\tR\rcallerNetwork\x12[\n" +
	"\x12request_attributes\x18\a \x01(\v2,.google.rpc.context.AttributeContext.RequestR\x11requestAttributes\x12`\n" +
	"\x16destination_attributes\x18\b \x01(\v2).google.rpc.context.AttributeContext.PeerR\x15destinationAttributes\"n\n" +
	"\x10ResourceLocation\x12+\n" +
	"\x11current_locations\x18\x01 \x03(\tR\x10currentLocations\x12-\n" +
	"\x12original_locations\x18\x02 \x03(\tR\x11originalLocations\"\x9c\x04\n" +
	"\x1cServiceAccountDelegationInfo\x12\x84\x01\n" +
	"\x15first_party_principal\x18\x01 \x01(\v2N.google.events.cloud.audit.v1.ServiceAccountDelegationInfo.FirstPartyPrincipalH\x00R\x13firstPartyPrincipal\x12\x84\x01\n" +
	"\x15third_party_principal\x18\x02 \x01(\v2N.google.events.cloud.audit.v1.ServiceAccountDelegationInfo.ThirdPartyPrincipalH\x00R\x13thirdPartyPrincipal\x1a\x82\x01\n" +
	"\x13FirstPartyPrincipal\x12'\n" +
	"\x0fprincipal_email\x18\x01 \x01(\tR\x0eprincipalEmail\x12B\n" +
	"\x10service_metadata\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x0fserviceMetadata\x1a\\\n" +
	"\x13ThirdPartyPrincipal\x12E\n" +
	"\x12third_party_claims\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x10thirdPartyClaimsB\v\n" +
	"\tAuthority\"U\n" +
	"\bLogSplit\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12!\n" +
	"\ftotal_splits\x18\x03 \x01(\x05R\vtotalSplits*\x82\x01\n" +
	"\vLogSeverity\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\t\n" +
	"\x05DEBUG\x10d\x12\t\n" +
	"\x04INFO\x10\xc8\x01\x12\v\n" +
	"\x06NOTICE\x10\xac\x02\x12\f\n" +
	"\aWARNING\x10\x90\x03\x12\n" +
	"\n" +
	"\x05ERROR\x10\xf4\x03\x12\r\n" +
	"\bCRITICAL\x10\xd8\x04\x12\n" +
	"\n" +
	"\x05ALERT\x10\xbc\x05\x12\x0e\n" +
	"\tEMERGENCY\x10\xa0\x06Bj\xaa\x02%Google.Events.Protobuf.Cloud.Audit.V1\xca\x02\x1cGoogle\\Events\\Cloud\\Audit\\V1\xea\x02 Google::Events::Cloud::Audit::V1b\x06proto3"

var (
	file_cloud_audit_v1_data_proto_rawDescOnce sync.Once
	file_cloud_audit_v1_data_proto_rawDescData []byte
)

func file_cloud_audit_v1_data_proto_rawDescGZIP() []byte {
	file_cloud_audit_v1_data_proto_rawDescOnce.Do(func() {
		file_cloud_audit_v1_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloud_audit_v1_data_proto_rawDesc), len(file_cloud_audit_v1_data_proto_rawDesc)))
	})
	return file_cloud_audit_v1_data_proto_rawDescData
}

var file_cloud_audit_v1_data_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cloud_audit_v1_data_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_cloud_audit_v1_data_proto_goTypes = []any{
	(LogSeverity)(0),                     // 0: google.events.cloud.audit.v1.LogSeverity
	(*LogEntryData)(nil),                 // 1: google.events.cloud.audit.v1.LogEntryData
	(*LogEntryOperation)(nil),            // 2: google.events.cloud.audit.v1.LogEntryOperation
	(*AuditLog)(nil),                     // 3: google.events.cloud.audit.v1.AuditLog
	(*AuthenticationInfo)(nil),           // 4: google.events.cloud.audit.v1.AuthenticationInfo
	(*AuthorizationInfo)(nil),            // 5: google.events.cloud.audit.v1.AuthorizationInfo
	(*RequestMetadata)(nil),              // 6: google.events.cloud.audit.v1.RequestMetadata
	(*ResourceLocation)(nil),             // 7: google.events.cloud.audit.v1.ResourceLocation
	(*ServiceAccountDelegationInfo)(nil), // 8: google.events.cloud.audit.v1.ServiceAccountDelegationInfo
	(*LogSplit)(nil),                     // 9: google.events.cloud.audit.v1.LogSplit
	nil,                                  // 10: google.events.cloud.audit.v1.LogEntryData.LabelsEntry
	(*ServiceAccountDelegationInfo_FirstPartyPrincipal)(nil), // 11: google.events.cloud.audit.v1.ServiceAccountDelegationInfo.FirstPartyPrincipal
	(*ServiceAccountDelegationInfo_ThirdPartyPrincipal)(nil), // 12: google.events.cloud.audit.v1.ServiceAccountDelegationInfo.ThirdPartyPrincipal
	(*api.MonitoredResource)(nil),                            // 13: google.api.MonitoredResource
	(*timestamppb.Timestamp)(nil),                            // 14: google.protobuf.Timestamp
	(*structpb.Struct)(nil),                                  // 15: google.protobuf.Struct
	(*status.Status)(nil),                                    // 16: google.rpc.Status
	(*attribute_context.AttributeContext_Resource)(nil),      // 17: google.rpc.context.AttributeContext.Resource
	(*attribute_context.AttributeContext_Request)(nil),       // 18: google.rpc.context.AttributeContext.Request
	(*attribute_context.AttributeContext_Peer)(nil),          // 19: google.rpc.context.AttributeContext.Peer
}
var file_cloud_audit_v1_data_proto_depIdxs = []int32{
	13, // 0: google.events.cloud.audit.v1.LogEntryData.resource:type_name -> google.api.MonitoredResource
	3,  // 1: google.events.cloud.audit.v1.LogEntryData.proto_payload:type_name -> google.events.cloud.audit.v1.AuditLog
	10, // 2: google.events.cloud.audit.v1.LogEntryData.labels:type_name -> google.events.cloud.audit.v1.LogEntryData.LabelsEntry
	2,  // 3: google.events.cloud.audit.v1.LogEntryData.operation:type_name -> google.events.cloud.audit.v1.LogEntryOperation
	14, // 4: google.events.cloud.audit.v1.LogEntryData.timestamp:type_name -> google.protobuf.Timestamp
	14, // 5: google.events.cloud.audit.v1.LogEntryData.receive_timestamp:type_name -> google.protobuf.Timestamp
	0,  // 6: google.events.cloud.audit.v1.LogEntryData.severity:type_name -> google.events.cloud.audit.v1.LogSeverity
	9,  // 7: google.events.cloud.audit.v1.LogEntryData.split:type_name -> google.events.cloud.audit.v1.LogSplit
	7,  // 8: google.events.cloud.audit.v1.AuditLog.resource_location:type_name -> google.events.cloud.audit.v1.ResourceLocation
	15, // 9: google.events.cloud.audit.v1.AuditLog.resource_original_state:type_name -> google.protobuf.Struct
	16, // 10: google.events.cloud.audit.v1.AuditLog.status:type_name -> google.rpc.Status
	4,  // 11: google.events.cloud.audit.v1.AuditLog.authentication_info:type_name -> google.events.cloud.audit.v1.AuthenticationInfo
	5,  // 12: google.events.cloud.audit.v1.AuditLog.authorization_info:type_name -> google.events.cloud.audit.v1.AuthorizationInfo
	6,  // 13: google.events.cloud.audit.v1.AuditLog.request_metadata:type_name -> google.events.cloud.audit.v1.RequestMetadata
	15, // 14: google.events.cloud.audit.v1.AuditLog.request:type_name -> google.protobuf.Struct
	15, // 15: google.events.cloud.audit.v1.AuditLog.response:type_name -> google.protobuf.Struct
	15, // 16: google.events.cloud.audit.v1.AuditLog.metadata:type_name -> google.protobuf.Struct
	15, // 17: google.events.cloud.audit.v1.AuditLog.service_data:type_name -> google.protobuf.Struct
	15, // 18: google.events.cloud.audit.v1.AuthenticationInfo.third_party_principal:type_name -> google.protobuf.Struct
	8,  // 19: google.events.cloud.audit.v1.AuthenticationInfo.service_account_delegation_info:type_name -> google.events.cloud.audit.v1.ServiceAccountDelegationInfo
	17, // 20: google.events.cloud.audit.v1.AuthorizationInfo.resource_attributes:type_name -> google.rpc.context.AttributeContext.Resource
	18, // 21: google.events.cloud.audit.v1.RequestMetadata.request_attributes:type_name -> google.rpc.context.AttributeContext.Request
	19, // 22: google.events.cloud.audit.v1.RequestMetadata.destination_attributes:type_name -> google.rpc.context.AttributeContext.Peer
	11, // 23: google.events.cloud.audit.v1.ServiceAccountDelegationInfo.first_party_principal:type_name -> google.events.cloud.audit.v1.ServiceAccountDelegationInfo.FirstPartyPrincipal
	12, // 24: google.events.cloud.audit.v1.ServiceAccountDelegationInfo.third_party_principal:type_name -> google.events.cloud.audit.v1.ServiceAccountDelegationInfo.ThirdPartyPrincipal
	15, // 25: google.events.cloud.audit.v1.ServiceAccountDelegationInfo.FirstPartyPrincipal.service_metadata:type_name -> google.protobuf.Struct
	15, // 26: google.events.cloud.audit.v1.ServiceAccountDelegationInfo.ThirdPartyPrincipal.third_party_claims:type_name -> google.protobuf.Struct
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_cloud_audit_v1_data_proto_init() }
func file_cloud_audit_v1_data_proto_init() {
	if File_cloud_audit_v1_data_proto != nil {
		return
	}
	file_cloud_audit_v1_data_proto_msgTypes[7].OneofWrappers = []any{
		(*ServiceAccountDelegationInfo_FirstPartyPrincipal_)(nil),
		(*ServiceAccountDelegationInfo_ThirdPartyPrincipal_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloud_audit_v1_data_proto_rawDesc), len(file_cloud_audit_v1_data_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cloud_audit_v1_data_proto_goTypes,
		DependencyIndexes: file_cloud_audit_v1_data_proto_depIdxs,
		EnumInfos:         file_cloud_audit_v1_data_proto_enumTypes,
		MessageInfos:      file_cloud_audit_v1_data_proto_msgTypes,
	}.Build()
	File_cloud_audit_v1_data_proto = out.File
	file_cloud_audit_v1_data_proto_goTypes = nil
	file_cloud_audit_v1_data_proto_depIdxs = nil
}
