// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.6
// source: firebase/database/v1/data.proto

package databasedata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The data within all Firebase Real Time Database reference events.
type ReferenceEventData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The original data for the reference.
	Data *structpb.Value `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// The change in the reference data.
	Delta         *structpb.Value `protobuf:"bytes,2,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferenceEventData) Reset() {
	*x = ReferenceEventData{}
	mi := &file_firebase_database_v1_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferenceEventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferenceEventData) ProtoMessage() {}

func (x *ReferenceEventData) ProtoReflect() protoreflect.Message {
	mi := &file_firebase_database_v1_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferenceEventData.ProtoReflect.Descriptor instead.
func (*ReferenceEventData) Descriptor() ([]byte, []int) {
	return file_firebase_database_v1_data_proto_rawDescGZIP(), []int{0}
}

func (x *ReferenceEventData) GetData() *structpb.Value {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReferenceEventData) GetDelta() *structpb.Value {
	if x != nil {
		return x.Delta
	}
	return nil
}

var File_firebase_database_v1_data_proto protoreflect.FileDescriptor

const file_firebase_database_v1_data_proto_rawDesc = "" +
	"\n" +
	"\x1ffirebase/database/v1/data.proto\x12\"google.events.firebase.database.v1\x1a\x1cgoogle/protobuf/struct.proto\"n\n" +
	"\x12ReferenceEventData\x12*\n" +
	"\x04data\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x04data\x12,\n" +
	"\x05delta\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05deltaB|\xaa\x02+Google.Events.Protobuf.Firebase.Database.V1\xca\x02\"Google\\Events\\Firebase\\Database\\V1\xea\x02&Google::Events::Firebase::Database::V1b\x06proto3"

var (
	file_firebase_database_v1_data_proto_rawDescOnce sync.Once
	file_firebase_database_v1_data_proto_rawDescData []byte
)

func file_firebase_database_v1_data_proto_rawDescGZIP() []byte {
	file_firebase_database_v1_data_proto_rawDescOnce.Do(func() {
		file_firebase_database_v1_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_firebase_database_v1_data_proto_rawDesc), len(file_firebase_database_v1_data_proto_rawDesc)))
	})
	return file_firebase_database_v1_data_proto_rawDescData
}

var file_firebase_database_v1_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_firebase_database_v1_data_proto_goTypes = []any{
	(*ReferenceEventData)(nil), // 0: google.events.firebase.database.v1.ReferenceEventData
	(*structpb.Value)(nil),     // 1: google.protobuf.Value
}
var file_firebase_database_v1_data_proto_depIdxs = []int32{
	1, // 0: google.events.firebase.database.v1.ReferenceEventData.data:type_name -> google.protobuf.Value
	1, // 1: google.events.firebase.database.v1.ReferenceEventData.delta:type_name -> google.protobuf.Value
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_firebase_database_v1_data_proto_init() }
func file_firebase_database_v1_data_proto_init() {
	if File_firebase_database_v1_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_firebase_database_v1_data_proto_rawDesc), len(file_firebase_database_v1_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_firebase_database_v1_data_proto_goTypes,
		DependencyIndexes: file_firebase_database_v1_data_proto_depIdxs,
		MessageInfos:      file_firebase_database_v1_data_proto_msgTypes,
	}.Build()
	File_firebase_database_v1_data_proto = out.File
	file_firebase_database_v1_data_proto_goTypes = nil
	file_firebase_database_v1_data_proto_depIdxs = nil
}
