// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.6
// source: cloud/memcache/v1/data.proto

package memcachedata

import (
	dayofweek "google.golang.org/genproto/googleapis/type/dayofweek"
	timeofday "google.golang.org/genproto/googleapis/type/timeofday"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Memcached versions supported by our service.
type MemcacheVersion int32

const (
	MemcacheVersion_MEMCACHE_VERSION_UNSPECIFIED MemcacheVersion = 0
	// Memcached 1.5 version.
	MemcacheVersion_MEMCACHE_1_5 MemcacheVersion = 1
)

// Enum value maps for MemcacheVersion.
var (
	MemcacheVersion_name = map[int32]string{
		0: "MEMCACHE_VERSION_UNSPECIFIED",
		1: "MEMCACHE_1_5",
	}
	MemcacheVersion_value = map[string]int32{
		"MEMCACHE_VERSION_UNSPECIFIED": 0,
		"MEMCACHE_1_5":                 1,
	}
)

func (x MemcacheVersion) Enum() *MemcacheVersion {
	p := new(MemcacheVersion)
	*p = x
	return p
}

func (x MemcacheVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemcacheVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_memcache_v1_data_proto_enumTypes[0].Descriptor()
}

func (MemcacheVersion) Type() protoreflect.EnumType {
	return &file_cloud_memcache_v1_data_proto_enumTypes[0]
}

func (x MemcacheVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemcacheVersion.Descriptor instead.
func (MemcacheVersion) EnumDescriptor() ([]byte, []int) {
	return file_cloud_memcache_v1_data_proto_rawDescGZIP(), []int{0}
}

// Different states of a Memcached instance.
type Instance_State int32

const (
	// State not set.
	Instance_STATE_UNSPECIFIED Instance_State = 0
	// Memcached instance is being created.
	Instance_CREATING Instance_State = 1
	// Memcached instance has been created and ready to be used.
	Instance_READY Instance_State = 2
	// Memcached instance is updating configuration such as maintenance policy
	// and schedule.
	Instance_UPDATING Instance_State = 3
	// Memcached instance is being deleted.
	Instance_DELETING Instance_State = 4
	// Memcached instance is going through maintenance, e.g. data plane rollout.
	Instance_PERFORMING_MAINTENANCE Instance_State = 5
)

// Enum value maps for Instance_State.
var (
	Instance_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "CREATING",
		2: "READY",
		3: "UPDATING",
		4: "DELETING",
		5: "PERFORMING_MAINTENANCE",
	}
	Instance_State_value = map[string]int32{
		"STATE_UNSPECIFIED":      0,
		"CREATING":               1,
		"READY":                  2,
		"UPDATING":               3,
		"DELETING":               4,
		"PERFORMING_MAINTENANCE": 5,
	}
)

func (x Instance_State) Enum() *Instance_State {
	p := new(Instance_State)
	*p = x
	return p
}

func (x Instance_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Instance_State) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_memcache_v1_data_proto_enumTypes[1].Descriptor()
}

func (Instance_State) Type() protoreflect.EnumType {
	return &file_cloud_memcache_v1_data_proto_enumTypes[1]
}

func (x Instance_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Instance_State.Descriptor instead.
func (Instance_State) EnumDescriptor() ([]byte, []int) {
	return file_cloud_memcache_v1_data_proto_rawDescGZIP(), []int{0, 0}
}

// Different states of a Memcached node.
type Instance_Node_State int32

const (
	// Node state is not set.
	Instance_Node_STATE_UNSPECIFIED Instance_Node_State = 0
	// Node is being created.
	Instance_Node_CREATING Instance_Node_State = 1
	// Node has been created and ready to be used.
	Instance_Node_READY Instance_Node_State = 2
	// Node is being deleted.
	Instance_Node_DELETING Instance_Node_State = 3
	// Node is being updated.
	Instance_Node_UPDATING Instance_Node_State = 4
)

// Enum value maps for Instance_Node_State.
var (
	Instance_Node_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "CREATING",
		2: "READY",
		3: "DELETING",
		4: "UPDATING",
	}
	Instance_Node_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"CREATING":          1,
		"READY":             2,
		"DELETING":          3,
		"UPDATING":          4,
	}
)

func (x Instance_Node_State) Enum() *Instance_Node_State {
	p := new(Instance_Node_State)
	*p = x
	return p
}

func (x Instance_Node_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Instance_Node_State) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_memcache_v1_data_proto_enumTypes[2].Descriptor()
}

func (Instance_Node_State) Type() protoreflect.EnumType {
	return &file_cloud_memcache_v1_data_proto_enumTypes[2]
}

func (x Instance_Node_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Instance_Node_State.Descriptor instead.
func (Instance_Node_State) EnumDescriptor() ([]byte, []int) {
	return file_cloud_memcache_v1_data_proto_rawDescGZIP(), []int{0, 1, 0}
}

type Instance_InstanceMessage_Code int32

const (
	// Message Code not set.
	Instance_InstanceMessage_CODE_UNSPECIFIED Instance_InstanceMessage_Code = 0
	// Memcached nodes are distributed unevenly.
	Instance_InstanceMessage_ZONE_DISTRIBUTION_UNBALANCED Instance_InstanceMessage_Code = 1
)

// Enum value maps for Instance_InstanceMessage_Code.
var (
	Instance_InstanceMessage_Code_name = map[int32]string{
		0: "CODE_UNSPECIFIED",
		1: "ZONE_DISTRIBUTION_UNBALANCED",
	}
	Instance_InstanceMessage_Code_value = map[string]int32{
		"CODE_UNSPECIFIED":             0,
		"ZONE_DISTRIBUTION_UNBALANCED": 1,
	}
)

func (x Instance_InstanceMessage_Code) Enum() *Instance_InstanceMessage_Code {
	p := new(Instance_InstanceMessage_Code)
	*p = x
	return p
}

func (x Instance_InstanceMessage_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Instance_InstanceMessage_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_memcache_v1_data_proto_enumTypes[3].Descriptor()
}

func (Instance_InstanceMessage_Code) Type() protoreflect.EnumType {
	return &file_cloud_memcache_v1_data_proto_enumTypes[3]
}

func (x Instance_InstanceMessage_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Instance_InstanceMessage_Code.Descriptor instead.
func (Instance_InstanceMessage_Code) EnumDescriptor() ([]byte, []int) {
	return file_cloud_memcache_v1_data_proto_rawDescGZIP(), []int{0, 2, 0}
}

// A Memorystore for Memcached instance
type Instance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Unique name of the resource in this scope including project and
	// location using the form:
	//
	//	`projects/{project_id}/locations/{location_id}/instances/{instance_id}`
	//
	// Note: Memcached instances are managed and addressed at the regional level
	// so `location_id` here refers to a Google Cloud region; however, users may
	// choose which zones Memcached nodes should be provisioned in within an
	// instance. Refer to [zones][google.cloud.memcache.v1.Instance.zones] field
	// for more details.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// User provided name for the instance, which is only used for display
	// purposes. Cannot be more than 80 characters.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Resource labels to represent user-provided metadata.
	// Refer to cloud documentation on labels for more details.
	// https://cloud.google.com/compute/docs/labeling-resources
	Labels map[string]string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The full name of the Google Compute Engine
	// [network](/compute/docs/networks-and-firewalls#networks) to which the
	// instance is connected. If left unspecified, the `default` network
	// will be used.
	AuthorizedNetwork string `protobuf:"bytes,4,opt,name=authorized_network,json=authorizedNetwork,proto3" json:"authorized_network,omitempty"`
	// Zones in which Memcached nodes should be provisioned.
	// Memcached nodes will be equally distributed across these zones. If not
	// provided, the service will by default create nodes in all zones in the
	// region for the instance.
	Zones []string `protobuf:"bytes,5,rep,name=zones,proto3" json:"zones,omitempty"`
	// Required. Number of nodes in the Memcached instance.
	NodeCount int32 `protobuf:"varint,6,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	// Required. Configuration for Memcached nodes.
	NodeConfig *Instance_NodeConfig `protobuf:"bytes,7,opt,name=node_config,json=nodeConfig,proto3" json:"node_config,omitempty"`
	// The major version of Memcached software.
	// If not provided, latest supported version will be used. Currently the
	// latest supported major version is `MEMCACHE_1_5`.
	// The minor version will be automatically determined by our system based on
	// the latest supported minor version.
	MemcacheVersion MemcacheVersion `protobuf:"varint,9,opt,name=memcache_version,json=memcacheVersion,proto3,enum=google.events.cloud.memcache.v1.MemcacheVersion" json:"memcache_version,omitempty"`
	// User defined parameters to apply to the memcached process
	// on each node.
	Parameters *MemcacheParameters `protobuf:"bytes,11,opt,name=parameters,proto3" json:"parameters,omitempty"`
	// Output only. List of Memcached nodes.
	// Refer to [Node][google.cloud.memcache.v1.Instance.Node] message for more
	// details.
	MemcacheNodes []*Instance_Node `protobuf:"bytes,12,rep,name=memcache_nodes,json=memcacheNodes,proto3" json:"memcache_nodes,omitempty"`
	// Output only. The time the instance was created.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Output only. The time the instance was updated.
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// Output only. The state of this Memcached instance.
	State Instance_State `protobuf:"varint,15,opt,name=state,proto3,enum=google.events.cloud.memcache.v1.Instance_State" json:"state,omitempty"`
	// Output only. The full version of memcached server running on this instance.
	// System automatically determines the full memcached version for an instance
	// based on the input MemcacheVersion.
	// The full version format will be "memcached-1.5.16".
	MemcacheFullVersion string `protobuf:"bytes,18,opt,name=memcache_full_version,json=memcacheFullVersion,proto3" json:"memcache_full_version,omitempty"`
	// List of messages that describe the current state of the Memcached instance.
	InstanceMessages []*Instance_InstanceMessage `protobuf:"bytes,19,rep,name=instance_messages,json=instanceMessages,proto3" json:"instance_messages,omitempty"`
	// Output only. Endpoint for the Discovery API.
	DiscoveryEndpoint string `protobuf:"bytes,20,opt,name=discovery_endpoint,json=discoveryEndpoint,proto3" json:"discovery_endpoint,omitempty"`
	// The maintenance policy for the instance. If not provided,
	// the maintenance event will be performed based on Memorystore
	// internal rollout schedule.
	MaintenancePolicy *MaintenancePolicy `protobuf:"bytes,21,opt,name=maintenance_policy,json=maintenancePolicy,proto3" json:"maintenance_policy,omitempty"`
	// Output only. Published maintenance schedule.
	MaintenanceSchedule *MaintenanceSchedule `protobuf:"bytes,22,opt,name=maintenance_schedule,json=maintenanceSchedule,proto3" json:"maintenance_schedule,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_cloud_memcache_v1_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_memcache_v1_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_cloud_memcache_v1_data_proto_rawDescGZIP(), []int{0}
}

func (x *Instance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Instance) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Instance) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Instance) GetAuthorizedNetwork() string {
	if x != nil {
		return x.AuthorizedNetwork
	}
	return ""
}

func (x *Instance) GetZones() []string {
	if x != nil {
		return x.Zones
	}
	return nil
}

func (x *Instance) GetNodeCount() int32 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *Instance) GetNodeConfig() *Instance_NodeConfig {
	if x != nil {
		return x.NodeConfig
	}
	return nil
}

func (x *Instance) GetMemcacheVersion() MemcacheVersion {
	if x != nil {
		return x.MemcacheVersion
	}
	return MemcacheVersion_MEMCACHE_VERSION_UNSPECIFIED
}

func (x *Instance) GetParameters() *MemcacheParameters {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *Instance) GetMemcacheNodes() []*Instance_Node {
	if x != nil {
		return x.MemcacheNodes
	}
	return nil
}

func (x *Instance) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Instance) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Instance) GetState() Instance_State {
	if x != nil {
		return x.State
	}
	return Instance_STATE_UNSPECIFIED
}

func (x *Instance) GetMemcacheFullVersion() string {
	if x != nil {
		return x.MemcacheFullVersion
	}
	return ""
}

func (x *Instance) GetInstanceMessages() []*Instance_InstanceMessage {
	if x != nil {
		return x.InstanceMessages
	}
	return nil
}

func (x *Instance) GetDiscoveryEndpoint() string {
	if x != nil {
		return x.DiscoveryEndpoint
	}
	return ""
}

func (x *Instance) GetMaintenancePolicy() *MaintenancePolicy {
	if x != nil {
		return x.MaintenancePolicy
	}
	return nil
}

func (x *Instance) GetMaintenanceSchedule() *MaintenanceSchedule {
	if x != nil {
		return x.MaintenanceSchedule
	}
	return nil
}

// Maintenance policy per instance.
type MaintenancePolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output only. The time when the policy was created.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Output only. The time when the policy was updated.
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// Description of what this policy is for. Create/Update methods
	// return INVALID_ARGUMENT if the length is greater than 512.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Required. Maintenance window that is applied to resources covered by this
	// policy. Minimum 1. For the current version, the maximum number of
	// weekly_maintenance_windows is expected to be one.
	WeeklyMaintenanceWindow []*WeeklyMaintenanceWindow `protobuf:"bytes,4,rep,name=weekly_maintenance_window,json=weeklyMaintenanceWindow,proto3" json:"weekly_maintenance_window,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *MaintenancePolicy) Reset() {
	*x = MaintenancePolicy{}
	mi := &file_cloud_memcache_v1_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenancePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenancePolicy) ProtoMessage() {}

func (x *MaintenancePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_memcache_v1_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenancePolicy.ProtoReflect.Descriptor instead.
func (*MaintenancePolicy) Descriptor() ([]byte, []int) {
	return file_cloud_memcache_v1_data_proto_rawDescGZIP(), []int{1}
}

func (x *MaintenancePolicy) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *MaintenancePolicy) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *MaintenancePolicy) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MaintenancePolicy) GetWeeklyMaintenanceWindow() []*WeeklyMaintenanceWindow {
	if x != nil {
		return x.WeeklyMaintenanceWindow
	}
	return nil
}

// Time window specified for weekly operations.
type WeeklyMaintenanceWindow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Allows to define schedule that runs specified day of the week.
	Day dayofweek.DayOfWeek `protobuf:"varint,1,opt,name=day,proto3,enum=google.type.DayOfWeek" json:"day,omitempty"`
	// Required. Start time of the window in UTC.
	StartTime *timeofday.TimeOfDay `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Required. Duration of the time window.
	Duration      *durationpb.Duration `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeeklyMaintenanceWindow) Reset() {
	*x = WeeklyMaintenanceWindow{}
	mi := &file_cloud_memcache_v1_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeeklyMaintenanceWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeeklyMaintenanceWindow) ProtoMessage() {}

func (x *WeeklyMaintenanceWindow) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_memcache_v1_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeeklyMaintenanceWindow.ProtoReflect.Descriptor instead.
func (*WeeklyMaintenanceWindow) Descriptor() ([]byte, []int) {
	return file_cloud_memcache_v1_data_proto_rawDescGZIP(), []int{2}
}

func (x *WeeklyMaintenanceWindow) GetDay() dayofweek.DayOfWeek {
	if x != nil {
		return x.Day
	}
	return dayofweek.DayOfWeek(0)
}

func (x *WeeklyMaintenanceWindow) GetStartTime() *timeofday.TimeOfDay {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *WeeklyMaintenanceWindow) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

// Upcoming maintenance schedule.
type MaintenanceSchedule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output only. The start time of any upcoming scheduled maintenance for this
	// instance.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Output only. The end time of any upcoming scheduled maintenance for this
	// instance.
	EndTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Output only. The deadline that the maintenance schedule start time can not
	// go beyond, including reschedule.
	ScheduleDeadlineTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=schedule_deadline_time,json=scheduleDeadlineTime,proto3" json:"schedule_deadline_time,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MaintenanceSchedule) Reset() {
	*x = MaintenanceSchedule{}
	mi := &file_cloud_memcache_v1_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceSchedule) ProtoMessage() {}

func (x *MaintenanceSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_memcache_v1_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenanceSchedule.ProtoReflect.Descriptor instead.
func (*MaintenanceSchedule) Descriptor() ([]byte, []int) {
	return file_cloud_memcache_v1_data_proto_rawDescGZIP(), []int{3}
}

func (x *MaintenanceSchedule) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *MaintenanceSchedule) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *MaintenanceSchedule) GetScheduleDeadlineTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduleDeadlineTime
	}
	return nil
}

type MemcacheParameters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output only. The unique ID associated with this set of parameters. Users
	// can use this id to determine if the parameters associated with the instance
	// differ from the parameters associated with the nodes. A discrepancy between
	// parameter ids can inform users that they may need to take action to apply
	// parameters on nodes.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// User defined set of parameters to use in the memcached process.
	Params        map[string]string `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemcacheParameters) Reset() {
	*x = MemcacheParameters{}
	mi := &file_cloud_memcache_v1_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemcacheParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemcacheParameters) ProtoMessage() {}

func (x *MemcacheParameters) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_memcache_v1_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemcacheParameters.ProtoReflect.Descriptor instead.
func (*MemcacheParameters) Descriptor() ([]byte, []int) {
	return file_cloud_memcache_v1_data_proto_rawDescGZIP(), []int{4}
}

func (x *MemcacheParameters) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemcacheParameters) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

// The data within all Instance events.
type InstanceEventData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. The Instance event payload. Unset for deletion events.
	Payload       *Instance `protobuf:"bytes,1,opt,name=payload,proto3,oneof" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceEventData) Reset() {
	*x = InstanceEventData{}
	mi := &file_cloud_memcache_v1_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceEventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceEventData) ProtoMessage() {}

func (x *InstanceEventData) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_memcache_v1_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceEventData.ProtoReflect.Descriptor instead.
func (*InstanceEventData) Descriptor() ([]byte, []int) {
	return file_cloud_memcache_v1_data_proto_rawDescGZIP(), []int{5}
}

func (x *InstanceEventData) GetPayload() *Instance {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Configuration for a Memcached Node.
type Instance_NodeConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Number of cpus per Memcached node.
	CpuCount int32 `protobuf:"varint,1,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty"`
	// Required. Memory size in MiB for each Memcached node.
	MemorySizeMb  int32 `protobuf:"varint,2,opt,name=memory_size_mb,json=memorySizeMb,proto3" json:"memory_size_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instance_NodeConfig) Reset() {
	*x = Instance_NodeConfig{}
	mi := &file_cloud_memcache_v1_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance_NodeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance_NodeConfig) ProtoMessage() {}

func (x *Instance_NodeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_memcache_v1_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance_NodeConfig.ProtoReflect.Descriptor instead.
func (*Instance_NodeConfig) Descriptor() ([]byte, []int) {
	return file_cloud_memcache_v1_data_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Instance_NodeConfig) GetCpuCount() int32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *Instance_NodeConfig) GetMemorySizeMb() int32 {
	if x != nil {
		return x.MemorySizeMb
	}
	return 0
}

type Instance_Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output only. Identifier of the Memcached node. The node id does not
	// include project or location like the Memcached instance name.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Output only. Location (GCP Zone) for the Memcached node.
	Zone string `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	// Output only. Current state of the Memcached node.
	State Instance_Node_State `protobuf:"varint,3,opt,name=state,proto3,enum=google.events.cloud.memcache.v1.Instance_Node_State" json:"state,omitempty"`
	// Output only. Hostname or IP address of the Memcached node used by the
	// clients to connect to the Memcached server on this node.
	Host string `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	// Output only. The port number of the Memcached server on this node.
	Port int32 `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	// User defined parameters currently applied to the node.
	Parameters    *MemcacheParameters `protobuf:"bytes,6,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instance_Node) Reset() {
	*x = Instance_Node{}
	mi := &file_cloud_memcache_v1_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance_Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance_Node) ProtoMessage() {}

func (x *Instance_Node) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_memcache_v1_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance_Node.ProtoReflect.Descriptor instead.
func (*Instance_Node) Descriptor() ([]byte, []int) {
	return file_cloud_memcache_v1_data_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Instance_Node) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Instance_Node) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *Instance_Node) GetState() Instance_Node_State {
	if x != nil {
		return x.State
	}
	return Instance_Node_STATE_UNSPECIFIED
}

func (x *Instance_Node) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Instance_Node) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Instance_Node) GetParameters() *MemcacheParameters {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type Instance_InstanceMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A code that correspond to one type of user-facing message.
	Code Instance_InstanceMessage_Code `protobuf:"varint,1,opt,name=code,proto3,enum=google.events.cloud.memcache.v1.Instance_InstanceMessage_Code" json:"code,omitempty"`
	// Message on memcached instance which will be exposed to users.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instance_InstanceMessage) Reset() {
	*x = Instance_InstanceMessage{}
	mi := &file_cloud_memcache_v1_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance_InstanceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance_InstanceMessage) ProtoMessage() {}

func (x *Instance_InstanceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_memcache_v1_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance_InstanceMessage.ProtoReflect.Descriptor instead.
func (*Instance_InstanceMessage) Descriptor() ([]byte, []int) {
	return file_cloud_memcache_v1_data_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Instance_InstanceMessage) GetCode() Instance_InstanceMessage_Code {
	if x != nil {
		return x.Code
	}
	return Instance_InstanceMessage_CODE_UNSPECIFIED
}

func (x *Instance_InstanceMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_cloud_memcache_v1_data_proto protoreflect.FileDescriptor

const file_cloud_memcache_v1_data_proto_rawDesc = "" +
	"\n" +
	"\x1ccloud/memcache/v1/data.proto\x12\x1fgoogle.events.cloud.memcache.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/type/dayofweek.proto\x1a\x1bgoogle/type/timeofday.proto\"\xbf\x0f\n" +
	"\bInstance\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12M\n" +
	"\x06labels\x18\x03 \x03(\v25.google.events.cloud.memcache.v1.Instance.LabelsEntryR\x06labels\x12-\n" +
	"\x12authorized_network\x18\x04 \x01(\tR\x11authorizedNetwork\x12\x14\n" +
	"\x05zones\x18\x05 \x03(\tR\x05zones\x12\x1d\n" +
	"\n" +
	"node_count\x18\x06 \x01(\x05R\tnodeCount\x12U\n" +
	"\vnode_config\x18\a \x01(\v24.google.events.cloud.memcache.v1.Instance.NodeConfigR\n" +
	"nodeConfig\x12[\n" +
	"\x10memcache_version\x18\t \x01(\x0e20.google.events.cloud.memcache.v1.MemcacheVersionR\x0fmemcacheVersion\x12S\n" +
	"\n" +
	"parameters\x18\v \x01(\v23.google.events.cloud.memcache.v1.MemcacheParametersR\n" +
	"parameters\x12U\n" +
	"\x0ememcache_nodes\x18\f \x03(\v2..google.events.cloud.memcache.v1.Instance.NodeR\rmemcacheNodes\x12;\n" +
	"\vcreate_time\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12E\n" +
	"\x05state\x18\x0f \x01(\x0e2/.google.events.cloud.memcache.v1.Instance.StateR\x05state\x122\n" +
	"\x15memcache_full_version\x18\x12 \x01(\tR\x13memcacheFullVersion\x12f\n" +
	"\x11instance_messages\x18\x13 \x03(\v29.google.events.cloud.memcache.v1.Instance.InstanceMessageR\x10instanceMessages\x12-\n" +
	"\x12discovery_endpoint\x18\x14 \x01(\tR\x11discoveryEndpoint\x12a\n" +
	"\x12maintenance_policy\x18\x15 \x01(\v22.google.events.cloud.memcache.v1.MaintenancePolicyR\x11maintenancePolicy\x12g\n" +
	"\x14maintenance_schedule\x18\x16 \x01(\v24.google.events.cloud.memcache.v1.MaintenanceScheduleR\x13maintenanceSchedule\x1aO\n" +
	"\n" +
	"NodeConfig\x12\x1b\n" +
	"\tcpu_count\x18\x01 \x01(\x05R\bcpuCount\x12$\n" +
	"\x0ememory_size_mb\x18\x02 \x01(\x05R\fmemorySizeMb\x1a\xd1\x02\n" +
	"\x04Node\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04zone\x18\x02 \x01(\tR\x04zone\x12J\n" +
	"\x05state\x18\x03 \x01(\x0e24.google.events.cloud.memcache.v1.Instance.Node.StateR\x05state\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x05R\x04port\x12S\n" +
	"\n" +
	"parameters\x18\x06 \x01(\v23.google.events.cloud.memcache.v1.MemcacheParametersR\n" +
	"parameters\"S\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bCREATING\x10\x01\x12\t\n" +
	"\x05READY\x10\x02\x12\f\n" +
	"\bDELETING\x10\x03\x12\f\n" +
	"\bUPDATING\x10\x04\x1a\xbf\x01\n" +
	"\x0fInstanceMessage\x12R\n" +
	"\x04code\x18\x01 \x01(\x0e2>.google.events.cloud.memcache.v1.Instance.InstanceMessage.CodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\">\n" +
	"\x04Code\x12\x14\n" +
	"\x10CODE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cZONE_DISTRIBUTION_UNBALANCED\x10\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bCREATING\x10\x01\x12\t\n" +
	"\x05READY\x10\x02\x12\f\n" +
	"\bUPDATING\x10\x03\x12\f\n" +
	"\bDELETING\x10\x04\x12\x1a\n" +
	"\x16PERFORMING_MAINTENANCE\x10\x05\"\xa5\x02\n" +
	"\x11MaintenancePolicy\x12;\n" +
	"\vcreate_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12t\n" +
	"\x19weekly_maintenance_window\x18\x04 \x03(\v28.google.events.cloud.memcache.v1.WeeklyMaintenanceWindowR\x17weeklyMaintenanceWindow\"\xb1\x01\n" +
	"\x17WeeklyMaintenanceWindow\x12(\n" +
	"\x03day\x18\x01 \x01(\x0e2\x16.google.type.DayOfWeekR\x03day\x125\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x16.google.type.TimeOfDayR\tstartTime\x125\n" +
	"\bduration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\bduration\"\xd9\x01\n" +
	"\x13MaintenanceSchedule\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12P\n" +
	"\x16schedule_deadline_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x14scheduleDeadlineTime\"\xb8\x01\n" +
	"\x12MemcacheParameters\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12W\n" +
	"\x06params\x18\x03 \x03(\v2?.google.events.cloud.memcache.v1.MemcacheParameters.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"i\n" +
	"\x11InstanceEventData\x12H\n" +
	"\apayload\x18\x01 \x01(\v2).google.events.cloud.memcache.v1.InstanceH\x00R\apayload\x88\x01\x01B\n" +
	"\n" +
	"\b_payload*E\n" +
	"\x0fMemcacheVersion\x12 \n" +
	"\x1cMEMCACHE_VERSION_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fMEMCACHE_1_5\x10\x01Bs\xaa\x02(Google.Events.Protobuf.Cloud.Memcache.V1\xca\x02\x1fGoogle\\Events\\Cloud\\Memcache\\V1\xea\x02#Google::Events::Cloud::Memcache::V1b\x06proto3"

var (
	file_cloud_memcache_v1_data_proto_rawDescOnce sync.Once
	file_cloud_memcache_v1_data_proto_rawDescData []byte
)

func file_cloud_memcache_v1_data_proto_rawDescGZIP() []byte {
	file_cloud_memcache_v1_data_proto_rawDescOnce.Do(func() {
		file_cloud_memcache_v1_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloud_memcache_v1_data_proto_rawDesc), len(file_cloud_memcache_v1_data_proto_rawDesc)))
	})
	return file_cloud_memcache_v1_data_proto_rawDescData
}

var file_cloud_memcache_v1_data_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_cloud_memcache_v1_data_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_cloud_memcache_v1_data_proto_goTypes = []any{
	(MemcacheVersion)(0),               // 0: google.events.cloud.memcache.v1.MemcacheVersion
	(Instance_State)(0),                // 1: google.events.cloud.memcache.v1.Instance.State
	(Instance_Node_State)(0),           // 2: google.events.cloud.memcache.v1.Instance.Node.State
	(Instance_InstanceMessage_Code)(0), // 3: google.events.cloud.memcache.v1.Instance.InstanceMessage.Code
	(*Instance)(nil),                   // 4: google.events.cloud.memcache.v1.Instance
	(*MaintenancePolicy)(nil),          // 5: google.events.cloud.memcache.v1.MaintenancePolicy
	(*WeeklyMaintenanceWindow)(nil),    // 6: google.events.cloud.memcache.v1.WeeklyMaintenanceWindow
	(*MaintenanceSchedule)(nil),        // 7: google.events.cloud.memcache.v1.MaintenanceSchedule
	(*MemcacheParameters)(nil),         // 8: google.events.cloud.memcache.v1.MemcacheParameters
	(*InstanceEventData)(nil),          // 9: google.events.cloud.memcache.v1.InstanceEventData
	(*Instance_NodeConfig)(nil),        // 10: google.events.cloud.memcache.v1.Instance.NodeConfig
	(*Instance_Node)(nil),              // 11: google.events.cloud.memcache.v1.Instance.Node
	(*Instance_InstanceMessage)(nil),   // 12: google.events.cloud.memcache.v1.Instance.InstanceMessage
	nil,                                // 13: google.events.cloud.memcache.v1.Instance.LabelsEntry
	nil,                                // 14: google.events.cloud.memcache.v1.MemcacheParameters.ParamsEntry
	(*timestamppb.Timestamp)(nil),      // 15: google.protobuf.Timestamp
	(dayofweek.DayOfWeek)(0),           // 16: google.type.DayOfWeek
	(*timeofday.TimeOfDay)(nil),        // 17: google.type.TimeOfDay
	(*durationpb.Duration)(nil),        // 18: google.protobuf.Duration
}
var file_cloud_memcache_v1_data_proto_depIdxs = []int32{
	13, // 0: google.events.cloud.memcache.v1.Instance.labels:type_name -> google.events.cloud.memcache.v1.Instance.LabelsEntry
	10, // 1: google.events.cloud.memcache.v1.Instance.node_config:type_name -> google.events.cloud.memcache.v1.Instance.NodeConfig
	0,  // 2: google.events.cloud.memcache.v1.Instance.memcache_version:type_name -> google.events.cloud.memcache.v1.MemcacheVersion
	8,  // 3: google.events.cloud.memcache.v1.Instance.parameters:type_name -> google.events.cloud.memcache.v1.MemcacheParameters
	11, // 4: google.events.cloud.memcache.v1.Instance.memcache_nodes:type_name -> google.events.cloud.memcache.v1.Instance.Node
	15, // 5: google.events.cloud.memcache.v1.Instance.create_time:type_name -> google.protobuf.Timestamp
	15, // 6: google.events.cloud.memcache.v1.Instance.update_time:type_name -> google.protobuf.Timestamp
	1,  // 7: google.events.cloud.memcache.v1.Instance.state:type_name -> google.events.cloud.memcache.v1.Instance.State
	12, // 8: google.events.cloud.memcache.v1.Instance.instance_messages:type_name -> google.events.cloud.memcache.v1.Instance.InstanceMessage
	5,  // 9: google.events.cloud.memcache.v1.Instance.maintenance_policy:type_name -> google.events.cloud.memcache.v1.MaintenancePolicy
	7,  // 10: google.events.cloud.memcache.v1.Instance.maintenance_schedule:type_name -> google.events.cloud.memcache.v1.MaintenanceSchedule
	15, // 11: google.events.cloud.memcache.v1.MaintenancePolicy.create_time:type_name -> google.protobuf.Timestamp
	15, // 12: google.events.cloud.memcache.v1.MaintenancePolicy.update_time:type_name -> google.protobuf.Timestamp
	6,  // 13: google.events.cloud.memcache.v1.MaintenancePolicy.weekly_maintenance_window:type_name -> google.events.cloud.memcache.v1.WeeklyMaintenanceWindow
	16, // 14: google.events.cloud.memcache.v1.WeeklyMaintenanceWindow.day:type_name -> google.type.DayOfWeek
	17, // 15: google.events.cloud.memcache.v1.WeeklyMaintenanceWindow.start_time:type_name -> google.type.TimeOfDay
	18, // 16: google.events.cloud.memcache.v1.WeeklyMaintenanceWindow.duration:type_name -> google.protobuf.Duration
	15, // 17: google.events.cloud.memcache.v1.MaintenanceSchedule.start_time:type_name -> google.protobuf.Timestamp
	15, // 18: google.events.cloud.memcache.v1.MaintenanceSchedule.end_time:type_name -> google.protobuf.Timestamp
	15, // 19: google.events.cloud.memcache.v1.MaintenanceSchedule.schedule_deadline_time:type_name -> google.protobuf.Timestamp
	14, // 20: google.events.cloud.memcache.v1.MemcacheParameters.params:type_name -> google.events.cloud.memcache.v1.MemcacheParameters.ParamsEntry
	4,  // 21: google.events.cloud.memcache.v1.InstanceEventData.payload:type_name -> google.events.cloud.memcache.v1.Instance
	2,  // 22: google.events.cloud.memcache.v1.Instance.Node.state:type_name -> google.events.cloud.memcache.v1.Instance.Node.State
	8,  // 23: google.events.cloud.memcache.v1.Instance.Node.parameters:type_name -> google.events.cloud.memcache.v1.MemcacheParameters
	3,  // 24: google.events.cloud.memcache.v1.Instance.InstanceMessage.code:type_name -> google.events.cloud.memcache.v1.Instance.InstanceMessage.Code
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_cloud_memcache_v1_data_proto_init() }
func file_cloud_memcache_v1_data_proto_init() {
	if File_cloud_memcache_v1_data_proto != nil {
		return
	}
	file_cloud_memcache_v1_data_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloud_memcache_v1_data_proto_rawDesc), len(file_cloud_memcache_v1_data_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cloud_memcache_v1_data_proto_goTypes,
		DependencyIndexes: file_cloud_memcache_v1_data_proto_depIdxs,
		EnumInfos:         file_cloud_memcache_v1_data_proto_enumTypes,
		MessageInfos:      file_cloud_memcache_v1_data_proto_msgTypes,
	}.Build()
	File_cloud_memcache_v1_data_proto = out.File
	file_cloud_memcache_v1_data_proto_goTypes = nil
	file_cloud_memcache_v1_data_proto_depIdxs = nil
}
