# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Test Library Generation

# Uses protos from HEAD of https://github.com/googleapis/google-cloudevents
# and tooling from the current branch to check library generation.
#
# If the generator fails, the check will fail. If the generator succeeds
# tests will run to establish changes in the tooling, event schemas, and testdata
# have not fallen out of sync.

on:
  pull_request:
    # Sync with test-generator-fallback.yml on.pull_request.paths-ignore
    paths:
      - 'tools/**'
      - 'generate-code.sh'
      - 'internal/**'
      - '.github/workflows/test-generator.yml'

jobs:

  test-generator:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    env:
      # Library & Data Source repos using side-by-side checkout.
      LIBRARY_CHECKOUT_PATH: library # sync with defaults.run.working-directory
      DATA_SOURCE_CHECKOUT_PATH: protos-source-repo

    steps:
    - name: Go Library > Checkout Repository
      uses: actions/checkout@v3
      with:
        path: ${{ env.LIBRARY_CHECKOUT_PATH }}
    
    - name: Proto Schemas > Checkout Repository
      uses: actions/checkout@v3
      with:
        repository: googleapis/google-cloudevents
        path: ${{ env.DATA_SOURCE_CHECKOUT_PATH }}

    - name: Set Environment
      # Validation Test execution requires absolute path to testdata.
      run: echo "GENERATE_DATA_SOURCE=${PWD}/${DATA_SOURCE_CHECKOUT_PATH}" | tee -a $GITHUB_ENV

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x

    - name: Install the generator
      run: bash tools/setup-generator.sh
      working-directory: ${{ env.LIBRARY_CHECKOUT_PATH }}

    - name: Run the generator
      run: bash ./generate-code.sh
      working-directory: ${{ env.LIBRARY_CHECKOUT_PATH }}
      env:
        GENERATE_PROTOC_PATH: tmp/protobuf/bin/protoc
        GOFLAGS: "-v"
